[add] ESCでモーダルを閉じる
twin-te/twinte-front pull request #192
Opened 2020-10-14 22:44 UTC by HosokawaR

## 概要
ESCキーで、モーダル、設定ウィンドウを閉じる動作を追加しました。

## やったこと・変更内容
常にESCキーイベントを待機させるためにVueの@keyup.escではなく、event lisnterを使用しました。
@watchで監視してイベントを動的に付加させるようにしました。

- Fix #183 

## 確認したこと

- [x] 実際に操作して確認した。

## 備考
Vue.jsとTypeScriptは駆け出しなので、アドバイスなどありましたら遠慮なく教えて下さいm(_ _)m

2020-10-18 00:32 UTC, HikaruEgashira requested changes
## EventListnerに関して

windowというアプリケーション全体のオブジェクトをコンポネントで呼び出すのはコード可読性が低くなるのであまり推奨できないです。

vueならeventlitnerは`v-on`で代用するようにしたい。

## 解決策

- 全体に適用させたいのなら、`src/layouts/default.vue`の全体要素に`@keyup.esc`みたいなのをつけてあげるのが良さそう
- ダイアログやナビゲーションのstate管理はvuexで行っているので、

```ts
this.$store.commit('visible/chDrawer', { display: false })
this.$store.commit('visible/chDetail', { display: false })
this.$store.commit('visible/chAdd', { display: false })
this.$store.commit('visible/chInfo', { display: false })
...
```

みたいな書き方をするか、このvuexを定義している`src/store/visible`に`onToggleDisplay`likeな関数を作る感じの実装にしてほしいです！

2020-10-18 06:39 UTC, HosokawaR commented
色々と迷ったのですが、defaultにkeyup.escをつけて、すべてのモーダルstatにcommitする形にしてみました。
無駄なcommitを送るのはどうかとおもったのですが、このやり方だとシンプルに記述できたので。
`tabindex="0"`はdivにキーイベントを送るためにつけました。[参考](https://stackoverflow.com/questions/49042667/vuejs-keyup-esc-on-div-element-is-not-working)

もっとこうしたらいいとかありましたら教えて下さい！

2020-10-21 08:12 UTC, HikaruEgashira approved these changes
処理はよさげー

2020-10-21 08:15 UTC, HikaruEgashira commented
Thank you

2020-10-21 08:15 UTC, merged