講義日程の日付の情報量を100%に変更
twin-te/twinte-front pull request #199
Opened 2020-11-29 12:25 UTC by HosokawaR

返信を見逃しプルリクが遅れました。すみませんm(_ _)m

## 概要
いままで講義日程が最初だけ表示されていたもの（ex: 秋A月5）を、情報量が100%の文字列になるよう（ex: 秋AB月56）に変更しました。

## やったこと・変更内容
サーバから渡される文字列を木構造（？）のような形に変更し、講義日程の情報が100%の文字列を生成します。

- Fix #145 

## 確認したこと

- [x] 「0-9」の一文字ずつで講義検索して、全ての講義日程でエラーが出ないことを確かめました。

## 備考
TypeScriptの書き方になれてないので汚い部分があったら指摘してほしいです。
**少々複雑なコードになってしまいメンテナンス性が低いのが懸念点です。**
分かりにくいので何時ぞやのフロント会議とかで話し合えたらと思います。

2020-11-29 12:29 UTC, HikaruEgashira commented
@SIY1121 
twinte-parserの逆パーサーみたいな処理?なので、パース前の文字列をtwinte-parser側で情報を持つようにしたほうがよさそう?

2020-11-29 12:32 UTC, HosokawaR commented
@HikaruEgashira 
正直僕もそっちのほうがいいなと思いながらコード書いてました笑
情報の重複ではありますが、バグも少なくなりそうだしパース前の情報を送る仕組みがいいかなと思います。

2020-11-29 12:34 UTC, SIY1121 commented
さっきのミーティングの通り、表示のためのデータ整形はフロントの責務でバックの責務じゃないから、フロントでやっていいと思われ。(ただ整形があまりにパフォーマンスに影響を与えるなら別途考えるべきかと)

2020-11-29 12:42 UTC, HikaruEgashira commented
情報量100%デコードできているのかがわからないので、テスト書いたほうがよさそう。
https://github.com/twin-te/twinte-parser/blob/master/src/parser.ts
でif文でわかれている処理分のテストを書いてほしいです:pray:

2020-11-29 12:44 UTC, HosokawaR commented
了解です！
テストに慣れてないのと、別件で報告が遅れる可能性があるので気長に待っていただけるとうれしいですm(__)m

2020-12-03 18:22 UTC, HikaruEgashira requested changes
テストいい感じなのでよさそう
コンフリクト直してください。 `git rebase dev`

ファイルが`components/utils`から`usecase`に移動されるはずです:pray:

2020-12-03 18:22 UTC, HikaruEgashira commented on src/components/utils/getLectureTimeAsStr.ts
> +}
一つにまとめる
Queuesにするのもありかも

2020-12-03 18:22 UTC, HikaruEgashira commented on src/components/utils/getLectureTimeAsStr.ts
> +type details = detail[]
型定義忘れてた :pray:

```suggestion
type Detail = {
  id: number
  module: string
  day: string
  period: number
  room: string
}

type Details = Detail[]
```

2020-12-03 18:22 UTC, HikaruEgashira commented on src/components/utils/getLectureTimeAsStr.ts
> +const reduceArr = function (arr: string[][]) {
アロー関数にするか関数にするか

```suggestion
const reduceArr = (arr: string[][]) => {
```


```suggestion
function reduceArr (arr: string[][]) {
```

2020-12-03 18:22 UTC, HikaruEgashira commented on src/components/utils/getLectureTimeAsStr.ts
> +      }
```suggestion
      const period = x.period === 0 ? "" : String(x.period)
```

2020-12-03 21:21 UTC, HosokawaR commented on src/components/utils/getLectureTimeAsStr.ts
> +}
理解不足で申し訳ないのですが、Queuesにするとはどういうことなのでしょうか(・・?

2020-12-04 00:31 UTC, HikaruEgashira commented on src/components/utils/getLectureTimeAsStr.ts
> +}
string[][1]の重複をキューに保持するようにするといいかもって思ったけど、思ったよりきれいにできなかった笑

2020-12-04 00:37 UTC, HikaruEgashira commented on src/components/utils/getLectureTimeAsStr.ts
> +}
ここは22~28行目を消してまとめるだけでいいかも

2020-12-04 13:45 UTC, HosokawaR commented
@HikaruEgashira 
すみません。行き詰まってしまったので質問させて下さい。
おそらく`git rebase dev`による影響でテストが失敗してしまいます。
現象を手順を追って説明すると…
テストのときだけ`getLectureTimeAsStr`が`undifined`を返してしまいます。
`yarn test`をした場合`compose_course_time.test.js`の`getLectureTimeAsStr`が`undifined`を返してしまいます。しかし`yarn dev`で`modelAddCustom.vue`から呼び出した場合は正常に動作します。また強制的に`getLectureTimeAsStr`を`retrun 'xxx'`にして試した場合も、同様にテストのときのみ`undifiend`になってしまします。
コミットを遡ってデバックしたところ、3b1196e0（テストを追加したコミット）の時点ですでにこの現象が発生したため、おそらく`git rebase dev`による影響かと予測しているのですが、それ以上がわかりませんでした…
お時間がある時で構いませんので、助言がいただけますと助かります。

2020-12-04 15:02 UTC, HikaruEgashira commented
jestのautomockをtrueにしました。
testファイルのimportあとに

```
jest.unmock('~/usecase/getLectureTimeAsStr')
```

いれてください

2020-12-04 15:54 UTC, HikaruEgashira commented
![sorry](https://user-images.githubusercontent.com/39324739/101184764-6efbfd80-3694-11eb-9917-84f292bf6e05.jpg)

2020-12-05 06:24 UTC, HosokawaR commented
![sticker (1)](https://user-images.githubusercontent.com/45098934/101235694-e0c45d80-370d-11eb-8c75-3fd6945461b0.png)

2020-12-05 06:50 UTC, HosokawaR commented
ぐだぐだで長引いてしまいましたが、なんとかおわりました(´・ω・｀)
確認をよろしくおねがいします。

2020-12-05 08:44 UTC, HikaruEgashira approved these changes
よさげ。
あとリベース後は`git push -f origin hosokawaR/fix-search-result-time`みたいにforce pushするとコミットが増えないと思う。
マージお願いします

2020-12-05 08:51 UTC, merged