update variables and rem
twin-te/twinte-front pull request #206
Opened 2021-01-20 12:50 UTC by KanadeNishizawa

## 概要
initされたscssに修正点があったので更新

## やったこと・変更内容
variables(主にcolorとshadow)の更新
rootのremの値を設定
Buttonで使われていた$primary-liner-large(もう無い)を消した
orientation: landscapeのメディアクエリを追加

## 確認したこと

## 備考

2021-01-20 13:00 UTC, KanadeNishizawa commented
おちとるやないかい

2021-01-20 13:01 UTC, HikaruEgashira commented
そりゃそうやわ、そこ前のままやもん

2021-01-20 13:03 UTC, HikaruEgashira commented
なおった

2021-01-20 13:05 UTC, KanadeNishizawa commented
心眼でapproveして欲しい :pray:

2021-01-20 13:44 UTC, HikaruEgashira approved these changes
```
Error: Undefined variable.
   ╷
55 │   box-shadow: $shadow-convex-hover;
   │               ^^^^^^^^^^^^^^^^^^^^
   ╵
  src/scss/_mixin.scss 55:15      button-hover()
```

を直してください:pray:

2021-01-20 13:57 UTC, HikaruEgashira requested changes
間違えた

2021-01-21 03:04 UTC, HikaruEgashira approved these changes

2021-01-22 04:34 UTC, merged