icon button を追加
twin-te/twinte-front pull request #207
Opened 2021-01-20 23:00 UTC by HosokawaR

## 概要
試しに icon button を追加しました。いい感じでしたら他の部品もガシガシ追加していこうと思います。
![image](https://user-images.githubusercontent.com/45098934/105250309-dde9d300-5bbc-11eb-9631-d47b863128ae.png)

## やったこと・変更内容

- icon button を追加

## 確認したこと

## 備考
 - icon font は material-fonts 前提の作りになっており、アイコン名を渡す感じですがそれで大丈夫でしょうか？
 - `sass` の 
 ```
&:active {
  color: $white;
  @include button-active;
  &:hover {
    @include button-active;
  }
}
```
において`:active`に`:hover`を重ねるコードが調べてもよく分からなかったので意図を教えてほしいです。
 - その他おかしな部分があれば遠慮なく教えて下さい。

2021-01-21 02:31 UTC, KanadeNishizawa commented
@HosokawaR 
お疲れ様です！
デザイン関連だけ2点コメントします。
ちょっと長くなります。

まず1点目で、remのサイズめっちゃ計算させてしまいすいません。。。
https://www.figma.com/file/ofC6dBEU96Tp3IlrobCtlJ/App-next?node-id=804%3A8287 を参照してもらいたく、スマホ版でのrootのfont-sizeは62.5%(1rem=10px)にするので、figma上の1pxを0.1remに換算していただけると:pray:
知る由もなかったと思うので本当に申し訳ないのですが、実は今のmainのSCSSは少し前のfigmaが反映されています。remを含め最新にした #206 をrebaseしてもらえるといい感じに実装できると思います。

2点目
> sass の
```
 &:active {
  color: $white;
  @include button-active;
  &:hover {
    @include button-active;
  }
 }
```
> において:activeに:hoverを重ねるコードが調べてもよく分からなかったので意図を教えてほしいです。

これの祖先が私の過去作のscssを移行したものなので、意図をお答えします。
実はIconButton(あとButtonも)の挙動は、押した後も再度クリックされるまでactive時のstyleが保持されることを想定していました。
こんな感じ↓

![ダウンロード (7)](https://user-images.githubusercontent.com/48097323/105260487-3925c080-5bd1-11eb-8b67-b6540415cfaa.gif)

デザインデータで該当する箇所はこの辺りです。

<img width="200
" alt="スクリーンショット 2021-01-21 10 08 23" src="https://user-images.githubusercontent.com/48097323/105260570-5ce90680-5bd1-11eb-9227-fd1abcd8b555.png">

<img width="200" alt="スクリーンショット 2021-01-21 10 08 01" src="https://user-images.githubusercontent.com/48097323/105260578-5f4b6080-5bd1-11eb-92c8-4860df85e3e5.png">

よって、
```
 data() {
    return { btnActive: false };
  } 
```
と`@click="isActive = !isActive"`、`` [`icon-button--active`]: this.btnActive``とかでクリックの度に--activeを付けたり外したりみたいなイメージでした。
そして、上記の挙動をさせるために、(押した直後は当然カーソルがbuttonの上に乗っているので)CSS上でhoverのstyle(67行目~)が適用されてしまうことを防ぐ意図で`:hover`に`btn-active`のmixinを記述してます。
    
ところが見落としがあり、出欠ボタンやこういうの↓等、activeのstyleを保持するのはマズいものがいくつかあって、今どうしようか考えてます。

<img width="200
" alt="スクリーンショット 2021-01-21 10 27 41" src="https://user-images.githubusercontent.com/48097323/105270312-e94af780-5bd8-11eb-9dae-7a920f20e082.png">


もちろんどちらのButtonも必要ですが、activeのstyleを保持するデザインの方が多いため、個人的には保持しないものをイレギュラーとして扱いたいです。理想はIconButton(Buttonも)にpropertyを追加して両パターン切り替えられることなんですが実現できる？のか・・・？
どうしましょう・・・。
(cc. @HikaruEgashira)

2021-01-21 12:40 UTC, HosokawaR commented
rem の件了解しました！計算はエディタが自動で変換してくれるので大丈夫です。
active の style を保持する件ですが、`:pauseActiveStyle="false"`で style の保持をON/OFFできるようにしてみました。こういうことでしょうか？
![AG_20210121_213550](https://user-images.githubusercontent.com/45098934/105352239-001d3880-5c31-11eb-8dca-8e08f2eb1892.gif)
もっときれいな実装があれば教えて下さい。

2021-01-22 04:33 UTC, KanadeNishizawa approved these changes
え、すごい
ありがとうございます！
ロジックのreviewはフロントに任せますが、デザイン部分はパーペキです！

2021-01-22 05:41 UTC, HikaruEgashira requested changes
いいね！

2021-01-22 05:41 UTC, HikaruEgashira commented on src/components/IconButton.vue
> +      isActive.value = props.pauseActiveStyle ? !isActive.value : false;
```suggestion
      isActive.value = props.pauseActiveStyle && !isActive.value;
```

2021-01-22 05:41 UTC, HikaruEgashira commented on src/components/Button.vue
> +      isActive.value = props.pauseActiveStyle ? !isActive.value : false;
```suggestion
      isActive.value = props.pauseActiveStyle && !isActive.value;
```
booleanは論理演算子を有効活用したほうがわかりやすいのでこっちに

2021-01-22 05:43 UTC, HikaruEgashira requested changes

2021-01-22 05:43 UTC, HikaruEgashira commented on src/App.vue
> +    :pauseActiveStyle="false"
true,falseは書かなくてよかったと思うので
```suggestion
```

2021-01-22 05:45 UTC, HikaruEgashira commented on src/App.vue
> +    :pauseActiveStyle="false"
デフォルトがtrueだった

2021-01-22 05:46 UTC, HosokawaR commented on src/components/IconButton.vue
> +      isActive.value = props.pauseActiveStyle ? !isActive.value : false;
この書き方は思いつかなったです。いいですね。

2021-01-22 17:09 UTC, SIY1121 reviewed
お疲れさまです！
ちょっと気になったところがあるのでコメントします
@HikaruEgashira のコードがベースになってると思うのでえがちゃんも確認してもらえると 🙏

2021-01-22 17:09 UTC, SIY1121 commented on src/components/IconButton.vue
> +    const handleClick = (e: any) => {
せっかくts使ってるので
型があるところは指定すると良いかなという提案です
```suggestion
    const handleClick = (e: MouseEvent) => {
```

2021-01-22 17:09 UTC, SIY1121 commented on src/components/IconButton.vue
> +      emit("click", e.target.value);
イベントの情報として `e.target.value` 渡している意図が知りたいです。

targetはクリック位置の要素になるので、アイコン部分をクリックすると`target`は`span` に、アイコンを避けるようにボタンを押すと `button` になります。
`span`に`value`プロパティは存在しないため`undefined`に、`button`の`value`はデフォルトで空文字なので、どちらにせよ、イベントに渡しても使い道が無い気がします

（個人的にはそもそも渡さないか、`e`そのものを渡すのが普通かな？と感じました）

2021-01-22 17:34 UTC, SIY1121 reviewed
もう一点、これは `pauseActiveStyle` 絡みの話ですが

1. input が独自に状態を持つと親からコントロールができないため避けるべき
2. そもそも普通のButtonとToggleButtonは役割が違うので分けるべき（殆どのUIフレームワークでも別）

と思いました。

1について補足すると、例えば
![image](https://user-images.githubusercontent.com/17082836/105523619-f0315180-5d21-11eb-8c58-a638fbabaf78.png)
これの「現在の学期へ」ボタンは、現在の学期が表示されてる場合にactiveになります。ドロップダウンで現在とは違う学期に移動した場合、active状態は解除されるべきです。
しかしボタン内に状態があると外から解除する方法がありません。
（一般的にinput系は状態は持たずに常に親からのpropsを表示し、変更を検知したら親にイベントを送出するように設計するのが良いかと思います）

2021-01-22 18:25 UTC, HosokawaR commented on src/components/IconButton.vue
> +    const handleClick = (e: any) => {
ありがとうございます。型をつけます！

2021-01-22 18:27 UTC, HosokawaR commented on src/components/IconButton.vue
> +      emit("click", e.target.value);
すみません…脳死で @HikaruEgashira 先輩のコードをコピーしたので意図はわかりません…

2021-01-22 18:29 UTC, HosokawaR commented
たしかに子コンポーネントに状態を乗せるのはあまりよくなさそうです。勉強になりました！ありがとうございます。

2021-01-23 14:26 UTC, HosokawaR commented
状態を子コンポーネントに持たせないようにして親が全部持つようにしました。
`App.vue`の↓のところです。
```
 const isBtnActive = ref({
    expand_more: false,
    edit: false,
    menu: false,
  });
```
また押したら状態を記憶するボタンとして`ToggleIconButton`を作成しました。

2021-01-23 15:11 UTC, SIY1121 commented
良いと思います！

2021-01-23 15:13 UTC, SIY1121 reviewed
これも @HikaruEgashira  のコードベースかもしれないけど確認お願いします

2021-01-23 15:14 UTC, SIY1121 commented on src/components/IconButton.vue
> +    },
この`onClick`って使ってないように見えるけど今後使う予定なのでしょうか

2021-01-23 15:14 UTC, SIY1121 commented on src/components/ToggleIconButton.vue
> +    },
ここも

2021-01-24 08:11 UTC, HikaruEgashira commented on src/components/IconButton.vue
> +    },
コンポネント利用する側で、@clickが未定義ってエラーでたので追加（https://github.com/znck/vue-developer-experience/tree/main/packages/typecheck）

2021-01-24 08:13 UTC, HikaruEgashira commented on src/components/IconButton.vue
> +      emit("click", e.target.value);
そっちのほうが使いやすいかなって思ったけど、
今振り返ると何も渡さなくてもいい派です（他のソースコードをコピペしました）

2021-01-24 08:17 UTC, HikaruEgashira approved these changes

2021-01-24 09:09 UTC, merged

2021-01-24 09:24 UTC, SIY1121 commented on src/components/IconButton.vue
> +    },
自分の環境だと消しても特にエラーは出なかったな、、、（そもそもVueDXのドキュメントが見当たらないからわからんけど）
emitされるイベントを明示したいなら https://v3.vuejs.org/guide/migration/emits-option.html#_3-x-behavior こっち使ったほうが良い気がするんだけどどうだろう？（PR閉じちゃってるけど補足です）

2021-01-25 10:47 UTC, HosokawaR commented on src/components/IconButton.vue
> +    },
僕の方でも同じエラーが出ました。`props`の明示的に`onXXX`を書かないとtypeエラーになる模様です。VScode、または npmパッケージの`vuedx-typecheck .`で確認しました。