checkbox toggleSwitch toggleButton を追加
twin-te/twinte-front pull request #208
Opened 2021-01-23 23:44 UTC by HosokawaR

## 概要
 - checkbox 
 - toggleSwitch 
 - toggleButton
を追加
![image](https://user-images.githubusercontent.com/45098934/105617070-9e6ef100-5e1f-11eb-9fac-c0f744ee90f3.png)

## 備考
 - 状態を子コンポーネントに持たせないように意識しました。
 - おかしな点がありましたら遠慮なくご指的ください。

2021-01-25 03:34 UTC, KanadeNishizawa approved these changes
design部分パーペキです、お疲れ様です！

2021-01-27 06:55 UTC, HikaruEgashira requested changes

2021-01-27 06:55 UTC, HikaruEgashira commented on src/components/ToggleButton.vue
> +      type: Object as () => Label,
```suggestion
      type: Object,
```
がいいんじゃない？

2021-01-27 06:55 UTC, HikaruEgashira commented on src/components/ToggleButton.vue
> +  whichSelected: string;
```suggestion
  whichSelected: "left" | "right";
```

2021-01-27 06:55 UTC, HikaruEgashira commented on src/components/ToggleButton.vue
> +    const handleChange = (select: "left" | "right", e: MouseEvent) => {
```suggestion
    const handleChange = (select: Select, e: MouseEvent) => {
```
みたいにしてPropsで型を共有したい

2021-01-29 13:37 UTC, HosokawaR commented on src/components/ToggleButton.vue
> +    const handleChange = (select: "left" | "right", e: MouseEvent) => {
変更点を push しました。「みたいにしてPropsで型を共有したい」というのはこういうことでしょうか…？

2021-01-29 13:45 UTC, HosokawaR commented
２点伺いたい点があります。

deploy failed の log を見たいのですが
![image](https://user-images.githubusercontent.com/45098934/106281122-23279800-6282-11eb-884e-40dca1d97ac5.png)
と言われてしまいました。解決策はあるでしょうか？

vue-developer-experience が型エラーを吐くのですが、`yarn dev`(`vite`)は動きます。この場合は vue-developer-experience に従ったほうがいいでしょうか？

2021-01-29 15:09 UTC, HikaruEgashira commented
viteは型見てないので、vuedxの型チェックに従って下さい。
多分yarn buildで型エラー出ると思います。

2021-01-29 15:13 UTC, HikaruEgashira commented
vue-roiterでSPAになったことにより、netlifyでnot found出たやつかな？
もしそうなら起きたら設定します

2021-02-06 03:47 UTC, HosokawaR commented
`yarn.lock` の変更は取り込まなかったほうが良かったでしょうか？毎回変更されるので取り込んだのですが…

2021-02-06 04:29 UTC, HikaruEgashira commented
yarn.lockが変わっちゃうのは僕の構築ミスだと思うので申し訳ないです
たしかにpostcss-focusが入ったり入らなかったりするので、とりあえず今度package.jsonに追加しておきます。

レビューできそうであれば、GitHubのRe-request reviewボタンを押して下さい:pray:

2021-02-06 04:44 UTC, HosokawaR commented
Re-request review てこうやって使うんですね！レビューお願いします。
> Propsで型を共有したい
のあたりがちょっとよく分からなかったので合ってるか確認してほしいです。

2021-02-06 04:52 UTC, HikaruEgashira approved these changes
PropTypeあったんですね感
ありがとうございます！！

2021-02-06 05:00 UTC, merged