add-modal
twin-te/twinte-front pull request #214
Opened 2021-02-06 06:38 UTC by hayato24s

## 概要
Modal、GrayFilterコンポーネントの追加

## 備考

レスポンシブができているか怪しい。
モーダルは幅も高さも固定長だが、Button,font-size,padding,marginなどのremで指定しているところは端末によってサイズが変わるため、タブレットやPCでは、コンテンツのエリアがデザインよりも小さくなってしまう。

2021-02-06 07:35 UTC, HikaruEgashira commented
@KanadeNishizawa レスポンシブ対応はcssとscriptどっちでしようか
scriptならこんなかんじでとる
https://vueuse.js.org/core/useMediaQuery/

2021-02-06 07:56 UTC, KanadeNishizawa commented
> @KanadeNishizawa レスポンシブ対応はcssとscriptどっちでしようか
> scriptならこんなかんじでとる
> https://vueuse.js.org/core/useMediaQuery/

基本的にCSSが良いな、そのためにmixinも作ったし

2021-02-06 08:21 UTC, KanadeNishizawa reviewed
めちゃ細かい部分だけコメントしましたが、ほぼパーペキでした!

2021-02-06 08:21 UTC, KanadeNishizawa commented on src/components/Modal.vue
> +  padding: 3.5rem 3.1rem 3.1rem 3.1rem; //borderを考慮
デザインデータでborderはinnerに設定しており(右のサイドバーで確認できます)、↓のコードでもbox-sizing: border-boxを設定してくれているので、ここはborderの幅を考慮しなくて大丈夫です。

2021-02-06 08:21 UTC, KanadeNishizawa commented on src/components/Modal.vue
> +    @include tab-and-pc {
「vhが768px以上」または「画面が横向きの場合」にdevice="pc-tab"を設定したいので、ここのメディアクエリ は
`@media only screen and (min-height: $pc-and-tab-height),(orientation: landscape) `になっていて欲しいです。
すでにあるmixinそのままだと不可能なので、そういう場合は新しいものを作ってしまってください！

2021-02-06 08:21 UTC, KanadeNishizawa commented on src/components/Modal.vue
> +    @include tab-and-pc {
こちらも上と同じ感じで

2021-02-06 10:43 UTC, KanadeNishizawa approved these changes
デザイン部分はバッチリです、ありがとうございます!

2021-02-06 10:55 UTC, HikaruEgashira requested changes
いい感じです。
ありがとう！

2021-02-06 10:55 UTC, HikaruEgashira commented on src/components/GrayFilter.vue
> +    };
```suggestion
    const handleClick = () => {
      emit("click");
    };
```

clickはこれに統一しときます。
templateで`$emit("click")`だけでもいいかも

2021-02-10 00:00 UTC, HikaruEgashira approved these changes
お疲れ！
マージまでお願いします:pray:

2021-02-10 12:33 UTC, merged