CourseTile と CourseDetail を追加
twin-te/twinte-front pull request #216
Opened 2021-02-06 14:41 UTC by HosokawaR

## 概要
CourseTile と CourseDetail を追加しました。

![image](https://user-images.githubusercontent.com/45098934/107121063-eb4dc100-683c-11eb-98ea-59ea3ef0203b.png)

## 確認したこと

- [x] type-check & lint
- [x] 動く

## 備考
CourseTile は右上ののみだけ動きます。アニメーションの指定がどこにもなかったのでとりあえず適当に button とおなじアニメーションを付与しました。問題があれば教えて下さい。

また `type-check` と `lint` が競合しているようです… 例えばコンポーネントのプロパティを `sample-prop` と書いた場合`type-check` がそんな型ないぞと言います。おそらく子コンポーネント側では`sampleProp`と定義しているからだと思います。反対に`sampleProp`と親コンポーネントに書くと、`lint`がハイフンを使え！と警告してきます。どうすればいいでしょうか…？

2021-02-06 14:50 UTC, HosokawaR commented
このようなエラーが`type-check`から出ます。
```
src/pages/index.vue:41:13 - error VueDX/TS2322: Type '{ "icon-name": string; item: string; value: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{}> & Pick<Readonly<{ iconName: string; item: string; value: string; } & {}> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "key" | ... 11 more ... | "value">'.
  Property 'iconName' is missing in type '{ "icon-name": string; item: string; value: string; }' but required in type 'Pick<Readonly<{ iconName: string; item: string; value: string; } & {}> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "key" | ... 11 more ... | "value">'.
 38 |       :state="tileStat"
 39 |       course-name="学校を考える"
 40 |       course-id="1A101"
    |            ~~~~
 41 |     ></CourseTile>
```

`Property 'iconName' is missing in type '{ "icon-name": string; item: string; value: string; }'`から`icon-name`ではダメだと思いました。

2021-02-06 15:24 UTC, HikaruEgashira commented
htmlとtsの命名規則の差異だと思います。
html側の `icon-name`と
ts側の `iconName`は
同値になるってやつじゃないかな、、

2021-02-07 03:19 UTC, HikaruEgashira requested changes
3点質問しました！
実装コストが高くなりそうだと感じたら、意見おねがい:pray:

2021-02-07 03:19 UTC, HikaruEgashira commented on src/pages/index.vue
> +import CourseTile from "../components/CourseTile.vue";
CourseTile.vue側で`export type State = ...`して

```suggestion
import CourseTile, {
  State as CourseTileState,
} from "../components/CourseTile.vue";
```

106行目を

```
const tileStat = ref<CourseTileState>("default");
```

が型安全

2021-02-07 03:31 UTC, HikaruEgashira commented
eslint修正いれた

2021-02-07 07:52 UTC, HosokawaR commented
的確なご指摘ありがとうございます！変更しました。

それと eslintrc の `vue/attribute-hyphenation` なのですが
```
twinte-front $ yarn lint
yarn run v1.22.10
$ eslint --ext .vue ./src

Oops! Something went wrong! :(

ESLint: 7.18.0

Error: .eslintrc:
        Configuration for rule "vue/attribute-hyphenation" is invalid:  error (you passed '"nev
        Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"never"').
                                                                       front/node_modules/@esli
    at ConfigValidator.validateRuleOptions (/mnt/d/works/twinte/twinte-front/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:142:ib/shared/config-validat23)
    at /mnt/d/works/twinte/twinte-front/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:197:18                                   node_modules/@eslint/esl
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/mnt/d/works/twinte/twinte-front/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:194:34)
    at ConfigValidator.validateConfigArray (/mnt/d/works/twinte/twinte-front/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:320:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/mnt/d/works/twinte/twinte-front/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/mnt/d/works/twinte/twinte-front/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at FileEnumerator._iterateFilesRecursive (/mnt/d/works/twinte/twinte-front/node_modules/eslint/lib/cli-engine/file-enumerator.js:440:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/mnt/d/works/twinte/twinte-front/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:49) 
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
の
```
Configuration for rule "vue/attribute-hyphenation" is invalid:  error (you passed '"nev
        Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"never"').
```
のように`never`ではなく`0, 1, 2`で渡せと言われたので変更しました。もしかしたら自分の環境のみの問題かもしれません。

2021-02-07 08:12 UTC, HikaruEgashira approved these changes
いい感じー
eslintの修正もありがとう

2021-02-07 08:14 UTC, merged