Revert "CourseTile と CourseDetail を追加"
twin-te/twinte-front pull request #217
Opened 2021-02-07 08:56 UTC by HosokawaR

@KanadeNishizawa 先輩をレビュワーに追加していなかったので revert
CourseTile のアニメーションを確認してもらいたいです。

2021-02-07 09:33 UTC, KanadeNishizawa requested changes
質問いただいたアニメーションはOKでした!
追加で申し訳ないのですが、コメントしたうちfont-sizeの表記だけ修正していただけると:pray:

2021-02-07 09:33 UTC, KanadeNishizawa commented on src/components/CourseTile.vue
> -  transition: $transition-box-shadow;
アニメーションばっちりです!

2021-02-07 09:33 UTC, KanadeNishizawa commented on src/components/CourseDetail.vue
> -  &__icon {
ここの`.course-detail-icon`というクラスで実装してくださっているアイコン部分、実は↓でも使われておりDecoratedIconという1つのコンポーネントにする想定でした。また今度AddCardを実装する時に切り分ければ良いので今回は修正しなくて大丈夫ですが、一応把握しておいてもらえると:pray:
<img width="648" alt="スクリーンショット 2021-02-07 18 11 17" src="https://user-images.githubusercontent.com/48097323/107142145-34526200-6970-11eb-9cb0-6c8e810ead05.png">

2021-02-07 09:33 UTC, KanadeNishizawa commented on src/components/CourseDetail.vue
> -    font-size: 1.2rem;
以下のfont-sizeはvariableが存在するので、ここに加えて該当箇所を変換してください…!
(font-sizeをはじめ、spacingやborder-radiusなど0.4で刻んでいる値には基本的に変数が与えられてます。0.4刻みではないものもある。)
<img width="307" alt="スクリーンショット 2021-02-07 18 24 07" src="https://user-images.githubusercontent.com/48097323/107142344-af684800-6971-11eb-8732-f1340438da1c.png">

2021-02-07 09:44 UTC, HikaruEgashira approved these changes

2021-02-07 20:32 UTC, HosokawaR commented on src/components/CourseDetail.vue
> -    font-size: 1.2rem;
font-size の件、了解しました！
font-size の変数について質問なのですが、ここのような例外的に 9px のようになっている場所も変数を追加して指定したほうがいいでしょうか？それとももしかして指定ミスでしょうか？
![image](https://user-images.githubusercontent.com/45098934/107158628-cd17ca80-69ce-11eb-95c8-53c5707f0c1c.png)

2021-02-07 20:37 UTC, HosokawaR commented on src/components/CourseDetail.vue
> -  &__icon {
了解です！AddCard を実装するときに DecoratedIcon として切り離しておきます。

2021-02-07 20:56 UTC, HosokawaR commented
今までに自分が作ったコンポーネントでも変数指定漏れがありましたので近日中に修正します…

2021-02-08 03:58 UTC, KanadeNishizawa commented on src/components/CourseDetail.vue
> -    font-size: 1.2rem;
この教室番号はミュータントとして生み出した(あんまり良くないですが、時間割ページのレイアウトはちょっと特殊なので仕方なく)ので共通化するつもりはありませんでした。
が、どうしようかなあ…「万が一他で使う可能性は考慮しておきたい、でもvariablesに0.9remが混ざるのは美しくない」って感じなので、この文字のweight,color,line-heightなども含めて決め打ちで設定したmixinを作るとかがベターかなと今思いました！
お願いできるでしょうか・・・！

2021-02-08 22:25 UTC, HosokawaR commented on src/components/CourseDetail.vue
> -    font-size: 1.2rem;
わかりました！今後はそのように対応します。ありがとうございます。

2021-02-09 03:27 UTC, KanadeNishizawa approved these changes
色々と後出しでお願いしてしまいすみませんでした・・・対応ありがとうございました！
OKです!

2021-02-09 03:28 UTC, merged