SidebarとSidebarContentを追加
twin-te/twinte-front pull request #221
Opened 2021-02-11 11:25 UTC by KanadeNishizawa

## 概要
Sidebarと、Sidebarに必要なSidebarContentを追加した。

### Sidebar
<img width="260"  src="https://user-images.githubusercontent.com/48097323/107629875-13f31200-6ca6-11eb-8681-58d2b5c4fee3.gif">

### SidebarContent
#### default
<img width="260" alt="スクリーンショット 2021-02-11 20 12 40" src="https://user-images.githubusercontent.com/48097323/107629951-2ec58680-6ca6-11eb-803d-22671e871c74.png">

#### link
<img width="260" alt="スクリーンショット 2021-02-11 20 12 46" src="https://user-images.githubusercontent.com/48097323/107629979-39801b80-6ca6-11eb-8103-56c126d4be27.png">

#### selected(カレント表示)
<img width="260" alt="スクリーンショット 2021-02-11 20 12 58" src="https://user-images.githubusercontent.com/48097323/107629996-43098380-6ca6-11eb-894b-1d7abf6653b7.png">

## 備考
アプリの実装時に設定した方が楽そうだったので、GrayFilterや表示のアニメーションはこの切り出しには含めていないです。

2021-02-11 11:30 UTC, KanadeNishizawa commented
一旦修正するのでdraftにしますー

2021-02-12 07:39 UTC, HikaruEgashira requested changes
心眼Request

2021-02-12 07:39 UTC, HikaruEgashira commented on src/components/Sidebar.vue
> +import { ref } from "vue";
```suggestion
import { defineComponent, ref } from "vue";
import SidebarContent from "./SidebarContent.vue";
import Button from "./Button.vue";
```

2021-02-12 07:39 UTC, HikaruEgashira commented on src/components/Sidebar.vue
> +    const handleClick = (e: any) => {
any消してー

2021-02-12 07:39 UTC, HikaruEgashira commented on src/components/SidebarContent.vue
> +    <span class="sidebar__icon material-icons">{{ iconName }}</span>
sidebar__iconにmaterial-iconsをincludeするのはどう？

2021-02-12 08:05 UTC, KanadeNishizawa commented on src/components/SidebarContent.vue
> +    <span class="sidebar__icon material-icons">{{ iconName }}</span>
ほんとだ、やばいmixin運用してた
どうしようかな・・・他のコンポーネントへの反映も含めたicon関係の修正PRとして分けたいから、今回は一旦スルーして！欲しい！

2021-02-13 04:49 UTC, HikaruEgashira commented on src/components/Sidebar.vue
> +    const handleClick = (e: any) => {
解決したらre-request reviewでお願いします:pray:

2021-02-13 05:32 UTC, KanadeNishizawa commented on src/components/Sidebar.vue
> +    const handleClick = (e: any) => {
おっと、そーりーそーりー

2021-02-14 06:15 UTC, HikaruEgashira approved these changes

2021-02-14 06:35 UTC, merged