add popup
twin-te/twinte-front pull request #224
Opened 2021-02-23 06:47 UTC by hayato24s

## 概要
Popupの追加

## やったこと・変更内容

- Popup コンポーネントの追加
- PopupContent コンポーネントの追加

## 備考

2021-02-23 09:17 UTC, HikaruEgashira commented
ナイスです！
あと今後index.vueは実実装で使いたいので、
Popupコンポネントをpreview.vueに置いてほしいです！！

2021-02-23 10:24 UTC, HikaruEgashira requested changes
review.vueに使用例を乗せる方向性にします！

2021-02-23 10:24 UTC, HikaruEgashira commented on src/components/PopupContent.vue
> +      type: String,
```suggestion
      type: String as PropType<"normal" | "danger">,
```
型でバリデーション

2021-02-23 10:24 UTC, HikaruEgashira commented on yarn.lock
> +  integrity sha512-t5Amxc3BIwi+M2mI0iy9yHKe5plYJUMbxpIBuMDR953J5s12ewRe3s8MLvQdlhAiNN8FTh9CBKU+mfdNgbWauw==
このあたりの変更は僕のミスかもしれないけど、消しといてー

2021-02-23 11:35 UTC, HikaruEgashira requested changes

2021-02-23 11:35 UTC, HikaruEgashira commented on src/components/PopupContent.vue
> +    <span v-show="link" class="material-icons popup-content__link">launch</span>
```suggestion
    <span v-if="link" class="material-icons popup-content__link">launch</span>
```
`v-show`は`display: none`だった気がする
linkは描画後に値が変化しないのでv-ifでDOMを描画しない感じがよろしいかと（昔の知識）

2021-02-23 11:35 UTC, HikaruEgashira commented on src/pages/preview.vue
> +      height: calc(56.7rem - 20.8rem);
このファイル内で変数とかにしたほうがわかりやすいかな @KanadeNishizawa

2021-02-23 11:47 UTC, hayato24s commented on src/pages/preview.vue
> +      height: calc(56.7rem - 20.8rem);
Modalコンポーネントに含めてしまうという手もあります。

2021-02-23 12:48 UTC, KanadeNishizawa commented on src/pages/preview.vue
> +      height: calc(56.7rem - 20.8rem);
要素のサイズはそれ自身に決めうちするよりは、親要素のサイズとか他の要素とのpaddingに依存する想定だったから、height:100%かな?
ついでに__titleはmodal-titleみたいなmixinにして、__contentsとともにModal.vueに含めるとよりオシャレ…

<img width="217" alt="スクリーンショット 2021-02-23 21 28 47" src="https://user-images.githubusercontent.com/48097323/108844408-6fff5400-761f-11eb-814c-c58ab2050e54.png">
<img width="313" alt="スクリーンショット 2021-02-23 21 28 15" src="https://user-images.githubusercontent.com/48097323/108844482-8a393200-761f-11eb-9682-54b9fd71db55.png">

2021-02-23 12:48 UTC, KanadeNishizawa commented on src/pages/preview.vue
> +      height: calc(56.7rem - 20.8rem);
contentsもModal共通のstyleなので

2021-02-24 02:18 UTC, HikaruEgashira requested changes
型チェックが失敗してるので

2021-02-24 02:18 UTC, HikaruEgashira commented on src/pages/preview.vue
> +    const popupData = [
popupcontent側で

`type Color = "normal" | "danger";`

を定義して

```suggestion
    const popupData: {
      value: string;
      link: boolean;
      onClick: Function;
      color: Color;
    }[] = [
```

とかしてほしい:pray:

2021-02-24 02:46 UTC, hayato24s commented on src/pages/preview.vue
> +    const popupData = [
popupDataの型はpreviewとpopupcontentのどちらに書けばいいですか？

2021-02-24 02:50 UTC, HikaruEgashira commented on src/pages/preview.vue
> +    const popupData = [
popupcontentで使わないので、previewだと思う。
popupDataを複数のページで使うようになったら、その時に移動しようかなー

2021-02-24 12:50 UTC, KanadeNishizawa reviewed
やたら長文になってしまいましたが、実際の修正お願いしたいポイントはそんなにないです。お願いしますー。

2021-02-24 12:50 UTC, KanadeNishizawa commented on src/pages/index.vue
>        <div class="title">Twin:teへようこそ！</div>
このページいまModalの中身がなくて、たぶんslotの部分を<template #title>とかで挟むの忘れてそう・・・？

2021-02-24 12:50 UTC, KanadeNishizawa commented on src/pages/index.vue
>        <div class="title">Twin:teへようこそ！</div>
該当する部分にコメント追加できないのでここに書くのですが、このモーダル下部の2つのbuttonを包んでいる.button-containerは不要です…! Modal.vueの方で作ってくださった"button"(こっちの名前を"button-container"にするとわかりやすいかも?)がflexの設定されたcontainerの役割を果たしているので

2021-02-24 12:50 UTC, KanadeNishizawa commented on src/pages/index.vue
>        <div class="title">Twin:teへようこそ！</div>
`//コンテンツの高さ`以下で記述してくれたcontentsのheightは、Modal.vueの方のmodal__contentsに`height:100%`の記述で解決するのでカットしていただいて大丈夫です。
Modalという枠の中でtitleとbuttonはそれぞれが絶対的なheightとmarginを持っており、contents部分はその残りの領域に表示するというイメージです！

同じく、このファイル内の.contentsに書かれた `width: 100%;  overflow:scroll`などもModal共通のスタイルなのでModal.vueのみに書いてあると嬉しいです。
また、contentsのmargin-topは、titleにmargin-bottomがあるのでカットしてもらえると…!

2021-02-24 12:51 UTC, HikaruEgashira approved these changes
コードはいい感じ！

2021-02-24 13:00 UTC, KanadeNishizawa commented
む、でもPopupのPRだからModalに関しては別PRで出したりリファクタリングのときに修正したりする方が良いかもしれない？

2021-02-24 13:02 UTC, KanadeNishizawa approved these changes
上のはいつか修正していただけると嬉しいです、とりまPopupパーペキだったのでapproveします!

2021-02-24 13:42 UTC, hayato24s commented
- Popupの追加
- Modalの修正

2021-02-24 13:48 UTC, hayato24s commented
- Popupの追加
- Modalの修正

2021-02-24 13:49 UTC, merged