Fix page header
twin-te/twinte-front pull request #226
Opened 2021-02-23 17:22 UTC by hayato24s

## 概要
page-headerをhome以外のページに対応させた。

## やったこと・変更内容
- 右側のボタンのアイコンを変更できるようにした。
- 左側のボタンのstateの管理を親コンポーネントができるようにした。

## 備考
preview.vueで確認できます。
PageHeaderとpreview.vueのPageHeaderの部分以外のコードは、add-popupと同じです。

2021-02-24 02:29 UTC, HikaruEgashira requested changes
修正リクエストありがとー

2021-02-24 02:29 UTC, HikaruEgashira commented on src/pages/preview.vue
> +    >
```suggestion
    <PageHeader
      atHome
      :calendar="{ month: 2, day: 23, week: '火', schedule: '通常日課' }"
    >
```
booleanはこの記法が直感的
falseなら記述しない

2021-02-24 02:29 UTC, HikaruEgashira commented on src/pages/preview.vue
> +        ></ToggleIconButton> </template
なんか空白あるけどなんのやつやろ:thniking_face:

2021-02-24 02:29 UTC, HikaruEgashira commented on src/components/PageHeader.vue
> -      ></ToggleIconButton>
@KanadeNishizawa 消していいやつ?
どこのUIかがわかってない

2021-02-24 02:29 UTC, HikaruEgashira commented on src/pages/preview.vue
> +    <PageHeader :atHome="false"
```suggestion
    <PageHeader
```

2021-02-24 03:00 UTC, KanadeNishizawa commented on src/components/PageHeader.vue
> -      ></ToggleIconButton>
<img width="361" alt="スクリーンショット 2021-02-24 11 40 21" src="https://user-images.githubusercontent.com/48097323/108940663-1f2b4200-7697-11eb-86c4-7b359421f43f.png">
これの右上のボタンだね

当初はページに合わせてPageHeader自体の種類を切り替えることでこのボタンの有無を切り替える意図でここに書いたんだけど、「右側のボタンのstateの管理を親コンポーネント側でしたい」という意向は聞いてた、がこの編集が正しいのかは私じゃわからないので判断して欲しいー

2021-02-24 03:17 UTC, hayato24s commented on src/components/PageHeader.vue
>        <div v-if="atHome">
calenderの描画の有無があるのでatHomeのままにしたいです。

2021-02-24 03:17 UTC, HikaruEgashira commented on src/components/PageHeader.vue
> -      ></ToggleIconButton>
なるほどー
消して、details画面で実装みたいな感じにします！

2021-02-24 13:39 UTC, KanadeNishizawa commented on src/components/PageHeader.vue
> +    }
この記述、wide-screenの場合でもtitleは常にHeaderにおける中央に配置したいので@include以下はなくて大丈夫です(もし他の意図があれば教えていただけると)!
またcolor: $text-mainはrootで設定されているので基本記述する必要ないですー

2021-02-24 14:15 UTC, hayato24s commented on src/components/PageHeader.vue
> +    }
<img width="775" alt="スクリーンショット 2021-02-24 23 10 55" src="https://user-images.githubusercontent.com/68944024/109012920-e66e8580-76f5-11eb-89cd-e515a82b5bc7.png">

Designガイドライン-v3の横向きのレイアウトを参考にしました。

2021-02-24 14:32 UTC, KanadeNishizawa commented on src/components/PageHeader.vue
> +    }
おお…そういえばそんなデザイン作った気がしてきた…
なんかこの画面見るとこっちの方が良い気がしてくるな…

2021-02-24 14:35 UTC, KanadeNishizawa commented on src/components/PageHeader.vue
> +    }
どうしようかな…
たぶんその画面はfigmaのauto-layout設定をわたしがミスったやつなんですが、画面がスーパーワイドになった時とか考慮すると左寄りの方が良い気がしてきたので、やっぱその記述ありでお願いしても良いですか…?(本当にごめんなさい)

2021-02-24 14:40 UTC, hayato24s commented on src/components/PageHeader.vue
> +    }
了解です！

2021-02-24 14:48 UTC, KanadeNishizawa approved these changes
いろいろ修正&改良してくださり助かりました! ありがとうございます!

2021-02-27 04:20 UTC, HikaruEgashira approved these changes

2021-02-27 04:20 UTC, HikaruEgashira commented on src/components/PageHeader.vue
> +      default: {},
calendar.monthとかなりそう

2021-02-27 04:29 UTC, HikaruEgashira commented
@hayato24s 最新のmainにリベースしたらプレビュー成功しそうなので、リベースしたらrequest reviewして下さい！

2021-02-27 13:00 UTC, HikaruEgashira approved these changes
ナイスです！
賢い！

2021-02-27 13:03 UTC, merged