Add modal
twin-te/twinte-front pull request #227
Opened 2021-02-25 05:55 UTC by hayato24s

## 概要
モーダルの追加

## やったこと・変更内容
- welcome-modalの追加
- delete-course-modalの追加
- colorがdangerのボタンを追加
- layoutがfillのボタンの修正

## 備考

2021-02-25 08:20 UTC, HikaruEgashira requested changes
詳細画面入ってたので見といた（別PRにするかPRの説明を修正するかして欲しいです！）

2021-02-25 08:20 UTC, HikaruEgashira commented on src/components/Modal.vue
> +  <div>
このdiv消したい
モチベはdivdivが読みにくいかなと思った

2021-02-25 08:20 UTC, HikaruEgashira commented on src/route.ts
> +  { path: "/:course_id", component: Details },
```suggestion
  { path: "/course/:course_id", component: Details },
```
良くなかったので

2021-02-25 08:20 UTC, HikaruEgashira commented on src/pages/index.vue
> +      <Button @click="login" size="medium" layout="fill" color="primary"
```suggestion
      <Button @click="$router.push('login')" size="medium" layout="fill" color="primary"
```

2021-02-25 09:59 UTC, KanadeNishizawa requested changes

2021-02-25 09:59 UTC, KanadeNishizawa commented on src/pages/details.vue
> +  &__contents__text {
BEM記法の公式ガイドライン(https://en.bem.info/methodology/quick-start/ のElementの項目参照)では「Elementが記述された要素」自体をネストするのはOKなのですが、`Block__Element__Element`みたいにclassの記述でElementをネストするのは避けた方が良いことになっているので、
```suggestion
  &__text {
```
が良いかなと思いました!

2021-02-25 09:59 UTC, KanadeNishizawa commented on src/pages/details.vue
> +      <p class="modal__contents__text">
```suggestion
      <p class="modal__text">
```

2021-02-25 09:59 UTC, KanadeNishizawa commented on src/pages/index.vue
> +      <p class="modal__contents__text">
```suggestion
      <p class="modal__text">
```

2021-02-25 09:59 UTC, KanadeNishizawa commented on src/pages/index.vue
> +      line-height: $multi-line;
こちらも上と同じ感じで:pray:

2021-02-25 14:01 UTC, KanadeNishizawa approved these changes
お疲れ様です、あざます!

2021-02-27 04:23 UTC, HikaruEgashira approved these changes
いい感じ

2021-02-27 08:35 UTC, merged