Add page details
twin-te/twinte-front pull request #228
Opened 2021-02-27 13:27 UTC by hayato24s

## 概要
授業詳細ページのレイアウト

## やったこと・変更内容
- `/course/_course_id`に授業詳細ページのレイアウトを追加
- 機能面はまだ、

## 聞きたいこと
- ポップアップから授業削除モーダルを開いた時のポップアップは閉じるのか、そのままかどうか
- ヘッダーの左側の戻るボタンを押した時の挙動

## 備考
- scssの書き方、class名や変数名の付け方がおかしくないか見て欲しいです。

2021-02-28 02:49 UTC, HikaruEgashira reviewed
- pc時のナビゲーションバー（サイドに常時表示）はApp.vueにつけようと思ってます。（未実装）
- バックグラウンドがmin-height: 100vhになるようにはしておきたい
- marginに$spacing変数使ったほうがいいかも
- html構造は見やすいので良さそう

2021-02-28 02:49 UTC, HikaruEgashira commented on src/pages/course/_course_id.vue
> +      update:modelValue="updateMemo"
```suggestion
```

v-model使うのでこの表記がいらなくなる。
scriptのupdateMemoも消して下さい:pray:

2021-03-01 08:40 UTC, hayato24s commented
index.htmlとApp.vueでdiv#appが重なってしまうので、App.vueのidをlayoutにしますか？

2021-03-01 11:40 UTC, HikaruEgashira commented
App.vueのdiv#appいらないね、、
layoutは set-layout ブランチで作業しているので、そこのブランチにリベースしてもらえるといい感じに作業できると思います！

2021-03-01 17:59 UTC, KanadeNishizawa commented on src/pages/course/_course_id.vue
> +        value="齋藤敏寿、齋藤敏寿、齋藤敏寿、齋藤敏寿、齋藤敏寿、齋藤敏寿、齋藤敏寿、齋藤敏寿"
じわる

2021-03-01 18:14 UTC, KanadeNishizawa commented
> ポップアップから授業削除モーダルを開いた時のポップアップは閉じるのか、そのままかどうか

閉じない想定です!

> ヘッダーの左側の戻るボタンを押した時の挙動

これはHome(index)に戻ります。というかすみません…今気づいたんですが、この科目詳細ページの場合、PageHaderで設定した「左上のボタンは画面が横長の時に消える」ルールはマズいですね。サイドバーでしかHomeに戻れなくなってしまう…。

2021-03-01 18:19 UTC, KanadeNishizawa approved these changes
見た目とstyleめちゃ良い感じでした!

2021-03-03 05:11 UTC, HikaruEgashira requested changes
layoutマージしたので

2021-03-03 05:11 UTC, HikaruEgashira commented on src/components/Layout.vue
> +    max-width: 900px;
```suggestion
```

2021-03-03 05:11 UTC, HikaruEgashira commented on src/pages/course/_course_id.vue
> +  overflow: scroll;
```suggestion
```
消してもいい？

2021-03-03 05:24 UTC, KanadeNishizawa commented on src/components/Layout.vue
> +    max-width: 900px;
ごめん、layout作る前だったからわたしが書いてって頼んでた…
home以外のページはこれ必要だから後でlayoutの方に書いておきます

2021-03-03 05:42 UTC, hayato24s commented on src/pages/course/_course_id.vue
> +  overflow: scroll;
すみません。僕のミスです。
headerは画面上部固定で、残りの部分がoverflow: scroll;でした。

2021-03-03 05:52 UTC, KanadeNishizawa commented on src/components/Layout.vue
> +    max-width: 900px;
Layoutにこの記述含めなかった理由思い出した、LayoutがApp.vueにセットされているから、ホームは100%, ホーム以外はmax-width:900pxとかができない気がした
こうやってそれぞれのページで設定するか、場合わけしたLayout自体をそれぞれのページにimportするしかない？気がした

2021-03-03 06:06 UTC, hayato24s commented on src/components/Layout.vue
> +    max-width: 900px;
ページの方に書きます。

2021-03-03 06:41 UTC, hayato24s commented
とりあえず、overflowとmax-widthだけ修正しました。
僕としては、先にこのPRをmergeしてもらって、後ほど先輩方の方でlayoutの修正をしてもらいたいです。

2021-03-03 06:45 UTC, HikaruEgashira approved these changes
オッケーです:+1::+1:
時間があれば詳細ページの値が変わるようにするか、他のコンポネントを作るとかも試してみて下さい！
コミットに他のやつ入ってるのが気になるけどいいやー（多分force pushだと消える）

2021-03-03 06:49 UTC, merged