Dropdown, ScheduleEditer を追加
twin-te/twinte-front pull request #229
Opened 2021-03-01 21:26 UTC by HosokawaR

## 概要
Dropdown, SchedudeEditer を追加しました。
![AG_20210302_055557](https://user-images.githubusercontent.com/45098934/109559976-b45a8a80-7b1e-11eb-9167-e8603cd6f527.gif)

## やったこと・変更内容
- Dropdown を追加
- SchedudeEditerを追加

## 確認したこと

- [x] typecheck lint format
- [x] 動く

## 備考
- [vue-click-away](https://github.com/VinceG/vue-click-away) を使用しました。DropDwonの範囲外をクリックしたときにオプションを閉じる動作に使用しております。あまりメジャーなライブラリではありませんが、同種のライブラリに比べて全面的に Composition API & Typescript に対応していたため使用しました。もしこのライブラリの使用に懸念がありましたらお教え下さい。別の手法を検討します。
-

2021-03-02 04:29 UTC, HikaruEgashira requested changes
`git rebase main` してもらえるとpreview.vueが生成されると思うので、index.vueに書いてる内容をpreview.vueに移植してもらえるといい感じです！

2021-03-02 04:29 UTC, HikaruEgashira commented on package.json
> +    "vue3-click-away": "^1.1.0",
これ便利やね

2021-03-02 04:29 UTC, HikaruEgashira commented on tsconfig.json
> +  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue", "src/components/ScheduleEditer.vue"]
```suggestion
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
```

2021-03-02 07:52 UTC, KanadeNishizawa requested changes

2021-03-02 07:52 UTC, KanadeNishizawa commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
秋学期とその他(Homeの「特殊」に表示される)も含めてもらえると!

2021-03-02 07:53 UTC, KanadeNishizawa commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
<img width="504" alt="スクリーンショット 2021-03-02 16 46 03" src="https://user-images.githubusercontent.com/48097323/109615880-cf0d1d80-7b77-11eb-82ad-5acf48d05c1f.png">

2021-03-02 14:03 UTC, HosokawaR commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
「ドロップダウン挙動」というところに「指定なし」という選択肢があるのですが、これは「全て」てきなニュアンスでしょうか…？もしそうなら未選択の指定なしとややこしいので「全て」「全学期」などいいかなとおもったのですがいかがでしょう。
![image](https://user-images.githubusercontent.com/45098934/109659771-663f9880-7bab-11eb-84a6-1fe040f950ab.png)

2021-03-02 16:19 UTC, HosokawaR commented on tsconfig.json
> +  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue", "src/components/ScheduleEditer.vue"]
すみません変な変更が入ってました。
消しときます！

2021-03-02 16:53 UTC, KanadeNishizawa commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
> 未選択の指定なしとややこしい

この「指定なし」項目は、「春Bって選択したけどやっぱ無しで!」みたいなときに、まさに未選択の「指定なし」へ戻すための選択肢です!
 ちなみにkdbの検索UI(「指示なし」はなんか違和感があった)を踏襲しています。

<img width="949" alt="スクリーンショット 2021-03-03 1 17 23" src="https://user-images.githubusercontent.com/48097323/109680124-8aa57000-7bbf-11eb-8059-6e19a713063a.png">

認識されている通り、この選択肢の意味する内容は「全て」=「フィルタリングなし」です。
- 最初の未選択の状態も「フィルタリングなし」を意味しているが、その後に「全て」という別の表現の項目が出てくると違う意味なのかと思われる恐れがあるから
- 初期値に「全て」ではなく「選択なし」という表現を使ったのは、「まだ選択していない」というニュアンスを強調したかったから(&kdbに合わせた)

デザインする際は上記の意図で言葉を選択していました。
ただ、個人の感覚にもよる&コメントいただいた内容も納得だったので、もし強いモチベがあれば「全て」へ変更します!

2021-03-03 03:12 UTC, HosokawaR commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
あ、なるほど。「選択なし」を押すと元の灰色の未選択状態に戻るということですね。選択なし、という選択肢があるのかと勘違いしてました。少し実装を変えます。

2021-03-03 03:13 UTC, HikaruEgashira commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
@KanadeNishizawa 
未選択状態に戻るっていらなくない？
ユーザーのどの行動を行うためのUI？

2021-03-03 03:17 UTC, KanadeNishizawa commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
上で言ってる、一度選択したものを戻すため
どれかを必ず選択しなきゃいけないドロップダウンでは無くていい項目だけど、今回は選択なし=フィルタリングなしっていう選択肢もあるから必要

2021-03-03 03:18 UTC, HikaruEgashira commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
任意ね
納得です！

2021-03-03 03:51 UTC, HosokawaR commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
一つ質問したいのですが、「指定なし」がこのような感じで初期選択されているということでしょうか？
![image](https://user-images.githubusercontent.com/45098934/109750093-274b2a80-7c1f-11eb-9821-adfff64f3c3c.png)

2021-03-03 04:33 UTC, KanadeNishizawa commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
質問は「他の選択肢を選んだときと同じ動作で初期状態に戻るのか？」という意味で合っているでしょうか？
提示されたスクショの通り、同じように初期状態に戻ります。kdbも同じです。

2021-03-04 02:30 UTC, HosokawaR commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
![image](https://user-images.githubusercontent.com/45098934/109901661-c6822780-7cdc-11eb-9f2d-bf84432b0c5e.png)
![image](https://user-images.githubusercontent.com/45098934/109901692-d39f1680-7cdc-11eb-98ea-1b7540df145e.png)
kdb のように指定なしも選択肢の一つ、ただし灰色、な感じにしました！
合っているでしょうか？

2021-03-04 03:24 UTC, HikaruEgashira requested changes
コード内部も細かく見てみたので確認よろです:pray:

2021-03-04 03:24 UTC, HikaruEgashira commented on src/components/Dropdown.vue
> +    const isOptionsShown = ref(false);
usetoggleがおすすめ
https://vueuse.org/shared/useToggle/
```suggestion
    const [isOptionsShown, toggleShown] = useToggle();
```

2021-03-04 03:24 UTC, HikaruEgashira commented on src/components/Dropdown.vue
> +@import "../scss/main.scss";
絶対パスにしようかなって思ってる（一部未完）
src通るやつは基本的に絶対パスにするように統一したほうがわかりやすいかな、ってなった
```suggestion
@import "~/scss/main.scss";
```

2021-03-04 03:24 UTC, HikaruEgashira commented on src/components/DropdownContent.vue
> +    :style="{ width: width }"
```suggestion
    :style="{ width }"
```

2021-03-04 03:24 UTC, HikaruEgashira commented on src/components/DropdownContent.vue
> +    @click="emitClickEvent"
長くする必要ないので省略
```suggestion
    @click="$emit('click')"
```

2021-03-04 03:24 UTC, HikaruEgashira commented on src/components/ScheduleEditer.vue
> +} from "../components/Dropdown.vue";
じわるので
```suggestion
} from "./Dropdown.vue";
```

2021-03-04 03:24 UTC, HikaruEgashira commented on src/components/ScheduleEditer.vue
> +  id: number;
`id`は消せるように見える
配列のインデックスで取れるので

2021-03-04 04:11 UTC, KanadeNishizawa commented on src/components/ScheduleEditer.vue
> +    const semesterOptions = ref<DropdownOptions>(["春A", "春B", "春C"]);
想定とピッタリです、対応いただきありがとうございます!

2021-03-04 04:13 UTC, KanadeNishizawa approved these changes
アニメーションがとてもエレガント
お疲れ様でした🙏

2021-03-04 14:02 UTC, HosokawaR commented on src/components/Dropdown.vue
> +    const isOptionsShown = ref(false);
こんなのがあったんですね。便利です！

2021-03-04 14:06 UTC, HosokawaR commented on src/components/ScheduleEditer.vue
> +  id: number;
id を振った利用は[このような理由](https://qiita.com/FumioNonaka/items/d1d9c9335116426a8316)だったのですが、確かに今回はあまり関係のない話しでしたので index で要素を特定するように変更しました。

2021-03-05 05:05 UTC, HikaruEgashira approved these changes
いい感じー
追加ページのレイアウトもお願いします:pray:

2021-03-05 15:17 UTC, merged