Add edit layout
twin-te/twinte-front pull request #237
Opened 2021-03-07 17:52 UTC by hayato24s

## 概要
授業情報の編集ページの追加

## やったこと
- disabledのButtonを追加
- LabeledTextField.vueの追加
- 詳細ページを`course/_course_id.vue` -> `course/_course_id/index.vue`に移動
- 詳細ページのmaskの追加
- 編集ページのレイアウトの追加

## 備考
- 編集ページは`course/_course_id/edit`で確認できます。

2021-03-08 09:34 UTC, KanadeNishizawa commented on src/pages/course/_course_id/edit.vue
> +.edit {
```suggestion
.edit {
max-width:900px
```

2021-03-08 09:34 UTC, KanadeNishizawa commented on src/pages/course/_course_id/edit.vue
> +    margin: $spacing-3 $spacing-0 $spacing-6;
こんな感じで最下部のbuttonはbuttonはeditに対して中央揃えにする想定でした。
過去のcomponentや私のレビュー忘れの修正部分があったので、この部分だけ直したcommitを加えさせていただきました:pray:
<img width="514" alt="スクリーンショット 2021-03-08 18 16 52" src="https://user-images.githubusercontent.com/48097323/110301945-0c702000-803c-11eb-8d76-d56ffb7c3c19.png">

2021-03-08 09:41 UTC, HikaruEgashira requested changes
コードはいい感じなので、
popupが下に埋もれた部分の修正までしていただけたら:pray:

2021-03-08 09:41 UTC, HikaruEgashira commented on src/pages/course/_course_id/edit.vue
> +      }
ネスト低くしときます
```suggestion
      if (schedules.value.length >= scheduleMax) return;
      schedules.value.push({
        semester: "指定なし",
        date: "指定なし",
        period: "指定なし",
      });
```

2021-03-08 09:42 UTC, KanadeNishizawa commented on src/pages/course/_course_id/index.vue
>      </template>
Popup以外の部分をクリックすると、開いていたPopupが閉じるのが理想なので、 `v-click-away="closePopupMenu"`みたいな感じで設定をお願いします!(index.vueとかDropdownで使われているやつ)

2021-03-08 13:40 UTC, hayato24s commented
popupの修正に結構苦戦しています。
maskはmask-imageではなく、backgroundを使ったやり方になるのでしょうか？

2021-03-09 13:51 UTC, KanadeNishizawa commented
> popupの修正に結構苦戦しています。
> maskはmask-imageではなく、backgroundを使ったやり方になるのでしょうか？
> popupがmask-imageをかけているdiv.courseに重なってしまうと、popupが透過されてしまう

_course_id.vue内に配置したpopupに`position:relative`と`z-index: (maskのdomより高く、GrayFilterより低い値)`を設定してみてください! 
Popupがmaskより下のレイヤーになってしまっていたことが原因だったようです。あとz-indexはpositionを設定しないと適用されないのでご注意ください。

2021-03-10 22:54 UTC, KanadeNishizawa approved these changes
style部分パーペキです:good_higero:

2021-03-10 22:54 UTC, HikaruEgashira requested changes
popupが迷走しそうなので、以下の修正を行ってほしいです。

popupコンポネントには一切変更はくわえずに、ページ側にv-click-awayを用いた閉じる処理を実装する。

2021-03-11 03:45 UTC, hayato24s commented
icon-buttonを押すと、popupが閉じてまたすぐに開いてしまうバグが発生。
v-click-awayと@clickで処理が被ってしまっている。

2021-03-11 06:21 UTC, HikaruEgashira requested changes
一行だけ修正箇所あるので、ついでに
_course_id/index.vueの211行目のページ移動も実装お願いします

```typescript
    const router = useRouter();
    const route = useRoute();
    const { course_id: courseId } = route.params;

    // editに移動
    router.push(`${courseId}/edit`);
```
とか？（他に短い方法あればそれで！）

2021-03-11 06:21 UTC, HikaruEgashira commented on src/pages/course/_course_id/index.vue
> +      if (showPopup.value === false) return;
なくても変わらないので
```suggestion
```

2021-03-11 07:56 UTC, HikaruEgashira approved these changes
ないすー

2021-03-11 07:57 UTC, merged