Add csv layout
twin-te/twinte-front pull request #244
Opened 2021-03-11 15:29 UTC by hayato24s

## 概要
csvファイルから授業を追加する画面のレイアウトを追加

## 備考
- pathは`/add/csv`
- csv.vueの161行目あたりを変更すると画面が変わります。
- 無効なcsvファイルをアップロードした時のデザインがよくわかりません。
- CardCourseの左右のbox-shadowが消えてるかも？（3枚目が現在、2枚目が修正したやつ）
<img width="598" alt="スクリーンショット 2021-03-11 23 33 54" src="https://user-images.githubusercontent.com/68944024/110810669-5de10f00-82c9-11eb-8a02-9928f7e773d8.png">
<img width="414" alt="スクリーンショット 2021-03-11 23 02 14" src="https://user-images.githubusercontent.com/68944024/110810684-61749600-82c9-11eb-8db3-8289da748703.png">
<img width="406" alt="スクリーンショット 2021-03-11 23 03 48" src="https://user-images.githubusercontent.com/68944024/110810689-62a5c300-82c9-11eb-8aba-57816e6ae383.png">

2021-03-12 04:27 UTC, HikaruEgashira requested changes
PC画面で微妙にスクロールします！
原因ちょっとわかんなかったけどこのPRで直したい:pray:

2021-03-12 04:27 UTC, HikaruEgashira commented on src/pages/add/csv.vue
> +        <template v-if="valid">
templateだめっぽいのでdivに

2021-03-12 04:27 UTC, HikaruEgashira commented on src/pages/add/csv.vue
> +            :key="course"
一意の文字列に。
idって必ずあると思うので
```suggestion
            :key="course.id"
```

2021-03-12 04:27 UTC, HikaruEgashira commented on src/pages/add/csv.vue
> +    const addCourse = (force: boolean = false) => {
falseで推論できるので不要
```suggestion
    const addCourse = (force = false) => {
```

2021-03-12 04:27 UTC, HikaruEgashira commented on src/pages/add/csv.vue
> +      <div class="courses__contents">
上と混ぜると消せそうな行

2021-03-12 07:37 UTC, KanadeNishizawa commented
> 無効なcsvファイルをアップロードした時のデザインがよくわかりません。
わからないポイントを具体的に教えていただければ!

> CardCourseの左右のbox-shadowが消えてるかも？（3枚目が現在、2枚目が修正したやつ）
「修正したやつ」ということは修正方法は判明しているということでしょうか? 現時点でのcommitでは解決されていないようなので、その修正方法を適用できない事情がある感じですか？

2021-03-12 08:08 UTC, hayato24s commented
無効なcsvをアップロードした時のデザインについて。maskはつけますか？ファイル名との距離は2.4remでオーケーでしょうか？
CardCourseについて、paddingとmarginを指定する場所を変えたら、修正できました。まだ、commitしていないのでこの後修正します。僕には違いがよくわからなかったので、念の為聞いた感じです。

2021-03-12 08:21 UTC, KanadeNishizawa commented
> 無効なcsvをアップロードした時のデザインについて。maskはつけますか？ファイル名との距離は2.4remでオーケーでしょうか？
2.4remであってます! maskは内包する要素がスクロールする場合に付けるもの(Modalはグラデーションマスクにすると違和感があるのでのぞく)なので、無効なcsvをアップロードした時は付けない想定です。

2021-03-12 08:27 UTC, KanadeNishizawa approved these changes

2021-03-12 08:27 UTC, KanadeNishizawa commented on src/pages/add/csv.vue
> +        <div v-else class="courses__warning">
"warning"というよりは"error"( 科目重複とかは禁止されているわけではないがユーザーに留意していて欲しいのでwarning, 無効な形式のファイルは普通に禁止なのでerrorみたいな分け方)なので、そんな感じの名前にして欲しいです!

2021-03-12 08:30 UTC, KanadeNishizawa commented
not yet app でした:bow:

2021-03-13 04:40 UTC, hayato24s commented
やっぱりCardCourseの左右の影が表示できません。
画像のやつはなぜできたか？Layout.vueで指定している左右のpaddingを.course__contentsで指定していたから。
自分が調べてみた限り、box-shadowはブロック要素の外側に余白が必要だが、.courseで`overflow-y: scroll;`を指定しているため、余白がなくなってしまったから表示できないと思われます。.courseでpaddingを指定すると影が表示できます。何か良い解決策はないでしょうか？

2021-03-13 05:51 UTC, KanadeNishizawa commented
`  margin-right: -($spacing-4);
  padding-right: $spacing-4;`
これを`.courses`に追記してみてください!
ネガティブマージンで親のクリップを無視してはみ出させてから、paddingを加えて元の大きさに戻すとこんな感じでできると思います。
(ちょっと無理矢理感あるんですがこの方法しかなさそうなので)

<img width="925" alt="スクリーンショット 2021-03-13 14 42 12" src="https://user-images.githubusercontent.com/48097323/111020663-ef0bcf00-840a-11eb-823d-7a07e3e98054.png">

2021-03-13 09:10 UTC, hayato24s commented
pc画面のスクロールの原因はおそらく、maskをかけている要素の子要素のheightの指定が正確ではないからだど思われます。

2021-03-14 12:34 UTC, HikaruEgashira approved these changes
いい感じー

2021-03-14 13:04 UTC, merged