Add dropdown addable
twin-te/twinte-front pull request #248
Opened 2021-03-13 09:02 UTC by hayato24s

DropdownAddable.vueの追加
previewで確認できます。

2021-03-13 09:39 UTC, KanadeNishizawa commented
ド正論すぎる……自分でもなぜチェックボックス にしなかったのかわからないです(死にたい)

2021-03-13 09:52 UTC, KanadeNishizawa commented
このままだとマジで意味のわからない役割のUIになってしまうのですが、せっかく時間を割いて完璧に実装してくださった(本当にありがとうございます…!)ので、これを元に挙動とかUXをアレンジして今後どこかで使える方法を考えてみます!

というわけでこれはapproveさせていただくのですが、今回の手動追加画面はチェックボックスにしましょう:bow_women:

2021-03-13 09:52 UTC, KanadeNishizawa approved these changes

2021-03-13 11:05 UTC, HikaruEgashira commented
CIで出ているエラーが修正されたら見るね

2021-03-14 00:59 UTC, HikaruEgashira requested changes
リファクタ関連お願いしますー

2021-03-14 00:59 UTC, HikaruEgashira commented on src/components/DropdownAddable.vue
> +    ];
これ周りの処理、entityフォルダに移動してほしいです:pray:

2021-03-14 00:59 UTC, HikaruEgashira commented on src/components/DropdownAddable.vue
> +      type: Array as PropType<{ value: string }[]>,
これがよくない？
```suggestion
      type: Array as PropType<string[]>,
```

2021-03-14 00:59 UTC, HikaruEgashira commented on src/components/Dropdown.vue
> +    width: 100%;
```suggestion
    width: $fit;
```

2021-03-14 01:59 UTC, hayato24s commented on src/components/DropdownAddable.vue
> +      type: Array as PropType<{ value: string }[]>,
`string[]`だとv-forでv-model使うときにエラーが出ちゃいます。

2021-03-14 04:16 UTC, HikaruEgashira commented on src/components/DropdownAddable.vue
> +      type: Array as PropType<{ value: string }[]>,
よくわからないけどナイス！

2021-03-14 07:36 UTC, hayato24s commented on src/components/DropdownAddable.vue
> +      type: Array as PropType<{ value: string }[]>,
いろいろ問題があったので、結局`{ value: string }[]`の方にしました。

2021-03-14 08:19 UTC, HikaruEgashira approved these changes
じわじわくるけど動くのでapprove。

2021-03-14 08:51 UTC, merged