授業の追加/授業の検索ページを追加
twin-te/twinte-front pull request #250
Opened 2021-03-14 15:53 UTC by HosokawaR

### 授業の追加/授業の検索ページを追加

- アニメーションは適当につけてしまいました。もっとこんなイメージ、とかあれば教えて下さい。
- 確認用として「色彩」で検索すると検索結果が出るようになっています。それ以外だと「一致する授業がありません」と表示されます。

<div style="display: flex">
  <img src="https://user-images.githubusercontent.com/45098934/111074581-ec060100-8526-11eb-9940-7533ac796c0a.png" width="250px">
  <img src="https://user-images.githubusercontent.com/45098934/111074596-08a23900-8527-11eb-8dfe-5d09765d7650.png" width="250px">
  <img src="https://user-images.githubusercontent.com/45098934/111074607-15269180-8527-11eb-9837-9af83cf3571d.png" width="250px">
  <img src="https://user-images.githubusercontent.com/45098934/111074614-22dc1700-8527-11eb-9378-5d4c811341e6.png" width="250px">
</div>

### `CourseCard`の型定義を`entity`に移動
`entity`ファイルや型計算の使い方が適切か不安です。

2021-03-14 15:57 UTC, HosokawaR commented on src/pages/add/search.vue
> +            <!-- </template> -->
本当はコメントアウトされいているように綺麗に書きたかったのですが、`type-check` が何故かエラーを吐きます。今回は応急的にコメントアウトしました。おそらく`type-check`の[バグ](https://github.com/znck/vue-developer-experience/search?q=v-if&type=issues)かと思います。

2021-03-15 00:51 UTC, HikaruEgashira approved these changes
いいと思いますー
ワザップですが、`指定なし`を変数（initialOptionとか）にすると楽です

2021-03-15 00:51 UTC, HikaruEgashira commented on src/pages/add/search.vue
> +            <!-- </template> -->
今みたいに
divでやって、TODOコメントで残しておく方針でオッケーです。
なんかのreactの記事で`<IF :condition="true">some code</IF>`みたいなifコンポネントを作ってる記事あったので余力があれば作ってみるのもいいかも

2021-03-15 00:51 UTC, HikaruEgashira commented on src/components/Button.vue
> +      default: false,
確かにfalseがいいね、、
これの他ページでの影響とかはどんな感じですか？

2021-03-15 01:00 UTC, HikaruEgashira approved these changes
issueにして後回しにしても、時間があれば取り組んでもいい内容なのでapprove

2021-03-15 01:00 UTC, HikaruEgashira commented on src/pages/add/search.vue
> +          @click="$router.push('/add')"
このあたりrouter.back()にしたら、統一感でそう（別PRでまとめてもいいかも）

2021-03-15 01:41 UTC, HosokawaR commented on src/components/Button.vue
> +      default: false,
影響はなさそうです。全文検索で一つ一つ調べたところ`:pauseActiveStyle="false"`を指定してあるか、押した瞬間に別画面になるかのどちらかでしたので問題はないかと思います。先輩が`button`を作ってくれた後に僕が`ToggleButton`を別に作ったので、`button`のデフォルト動作はトグルしないにしました。

2021-03-15 01:43 UTC, HosokawaR commented on src/pages/add/search.vue
> +          @click="$router.push('/add')"
了解です。別PRでまとめて作業します。

2021-03-15 02:07 UTC, HosokawaR commented on src/pages/add/search.vue
> +              @click="search"
了解です。とりあえずここの検索部分にだけ `keyup` をつけときます。他の全ての button にも `keyup` つけたほうがいいでしょうか？したほうがいいなら変更しておきます。

2021-03-16 01:47 UTC, KanadeNishizawa requested changes
1点だけ、まだ何も検索していない場合は「一致する授業がありません」のメッセージは無しでお願いします! 何か検索して、結果がない場合にのみ表示したいので

2021-03-16 01:59 UTC, HikaruEgashira commented on src/pages/add/search.vue
> +              @click="search"
とりあえず検索のみでー

2021-03-16 10:53 UTC, KanadeNishizawa approved these changes
アニメーションもめっちゃ綺麗です、お疲れ様でした！

2021-03-16 15:01 UTC, merged