Add home logic
twin-te/twinte-front pull request #264
Opened 2021-03-20 08:50 UTC by hayato24s

- ホーム画面のロジックの追加
- dayjsの修正

### 追加したユースケース
- courseListToTable
- getCalendar
- getCourseList
- getCurrentModule
- getEvents

2021-03-20 12:09 UTC, HikaruEgashira requested changes
Array系だけ確認お願いします:pray:
動くかどうかはデバッグ作業で細かく確認するので、今のとこ目立った問題点はないと思います！

2021-03-20 12:09 UTC, HikaruEgashira commented on src/pages/index.vue
>      };
useSidebarがあるので使って下さい:pray:
ついでにtoggleSidebarをuseSidebarに移植してください:higero:

2021-03-21 02:23 UTC, HikaruEgashira approved these changes
修正終わった後にrerequestまでお願いします:pray:
portsの修正もあるので早めにapprove

2021-03-21 06:14 UTC, KanadeNishizawa approved these changes

2021-03-21 06:27 UTC, HosokawaR approved these changes

2021-03-21 09:48 UTC, merged