授業の手動追加ロジックを実装
twin-te/twinte-front pull request #266
Opened 2021-03-21 10:33 UTC by HosokawaR

- Schdule と Home の `day` など概念が重複した型をいくつか整理しました
- 授業の重複確認などは他のページと共通するところがあるので別ブランチで実装する予定です。

TypeScript がわからなくなってきたのでおかしなところが多々あります。よりやり方がありましたらぜひご指摘下さい。

2021-03-21 12:40 UTC, HikaruEgashira requested changes
day.tsとmodule.tsがカオスやけど、一旦カオスのままにします。
リベースめんどくなりそうだけどお願いします:pray:

2021-03-21 12:40 UTC, HikaruEgashira commented on src/entities/course.ts
> +};
staticなのでこれで良いはず
```suggestion
export const initCourse: FullRegisteredCourseWithoutID = {
    absence: 0,
    attendance: 0,
    credit: 0,
    instructor: "",
    late: 0,
    memo: "",
    methods: [],
    name: "",
    schedules: [],
    tags: [],
    year: 0,
  };
```

2021-03-21 12:40 UTC, HikaruEgashira commented on src/entities/course.ts
> +};
schedule.tsつくったのでリベースしてもらえると:pray:

2021-03-21 12:40 UTC, HikaruEgashira commented on src/entities/period.ts
> +  | "0"
0とその他の違いあるっけ？「ピリオドがゼロかー:thinkng_face:」ってなっちゃう

2021-03-21 12:40 UTC, HikaruEgashira commented on src/pages/add/manual.vue
> +      });
再代入は一回で！
```suggestion
      course.schedules = formatSchedule(schedules.value).map((v) => ({
        ...v,
        room: room.value,
      }));
```

2021-03-21 12:40 UTC, HikaruEgashira commented on src/usecases/addCourseByManual.ts
> +    return false;
return typeがややこしくなっちゃうのでnullにしたい。
```suggestion
    return null;
```

2021-03-21 12:40 UTC, HikaruEgashira commented on src/usecases/addCourseByManual.ts
> +import { usePorts } from "~/usecases/index";
```suggestion
```

2021-03-21 12:40 UTC, HikaruEgashira commented on src/usecases/addCourseByManual.ts
> +  credit: course.credit ?? -1,
-1?

2021-03-21 12:40 UTC, HikaruEgashira commented on src/usecases/addCourseByManual.ts
> +    if (status !== 200) throw "Result is NOT 200";
多分リベースしたらaxiosでthrowしてくれると思います
```suggestion
    const registeredCourse = await api.registered_courses.$post({
      body: formatCourse(course),
    });
```

2021-03-21 15:43 UTC, HosokawaR commented on src/usecases/addCourseByManual.ts
> +  credit: course.credit ?? -1,
必須プロパティだったので、`credit`（単位数）の初期値を`-1`にしました。ただマジックナンバーすぎるよなとも思っています… ベストな方法があれば知りたいです。

2021-03-21 16:11 UTC, HosokawaR commented on src/entities/period.ts
> +  | "0"
自分でも0の意味がわからなかったので消しました

2021-03-21 16:12 UTC, HosokawaR commented on src/entities/course.ts
> +};
教えてもらったところでアレなのですが、ここは`Required<RegisteredCourseWithoutID >`に変更しました。

2021-03-21 16:32 UTC, KanadeNishizawa approved these changes
「保存を押す→追加される」の部分はこのPRには含まない…? 
含まない前提で見た感じは問題なさそうでした!

2021-03-22 02:13 UTC, HikaruEgashira commented on src/entities/course.ts
> +};
それ思ったけど下記忘れてた

2021-03-22 02:15 UTC, HikaruEgashira commented on src/usecases/addCourseByManual.ts
> +  credit: course.credit ?? -1,
0じゃない？
総単位数を計算するときに減少するから加算に影響しない-1かなって思います（ついでに普通の授業に0はないので）

2021-03-22 02:37 UTC, HikaruEgashira commented on src/entities/course.ts
> +};
あ、でも`() => Required<RegisteredCourseWithoutID>`は`Required<RegisteredCourseWithoutID>`がいいな

2021-03-22 13:01 UTC, hayato24s approved these changes

2021-03-23 00:40 UTC, HikaruEgashira commented on src/usecases/addCourseByManual.ts
> +    return false;
csvでやってたvoid返すやつでもいいかもね

2021-03-23 04:37 UTC, HosokawaR commented on src/usecases/addCourseByManual.ts
> +  credit: course.credit ?? -1,
確かに0のほうが計算に影響しなくていいですね。その視点はなかったです。ありがとうございます。

2021-03-23 04:41 UTC, HosokawaR commented on src/entities/course.ts
> +};
`getInitCourse()`という関数じゃなくて`initCourse`という初期値でいいやん、という話しですか？

2021-03-23 04:54 UTC, HosokawaR commented on src/usecases/addCourseByManual.ts
> +    return false;
いいですね。ここは`void 0`にします。
`null`と`undefined`の扱いは統一したい感はありますよね。`void 0` = `undedined`で、さらに`null == undefined`は`true`になるので、ここは`null`でも`void 0`でもどっちでも動作は変わりません。変わらないのに`null`と`undefined`の２つの型があるのは混乱します。
[Micorosft のガイドライン](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#null-and-undefined)では`null` は使わず `undefined` に統一すると書いてあったりします。

2021-03-23 08:38 UTC, HikaruEgashira commented on src/entities/course.ts
> +};
それです！

2021-03-23 08:58 UTC, HikaruEgashira commented on src/usecases/addCourseByManual.ts
> +    return false;
undefinedはフロント側が定義してないような値にのみ使われるのでreturn undefinedとかはしないほうがよく、nullは値が存在しないことを表すので、正常な処理をおこなったが値はないときとかに使う。return  undefinedになりそうなときはreturn nullの方が直感的。void 0はundefinedと同じだか、voidを返すときに利用するのはいいかも（自分はvoidは返すぐらいなら例外をcatchする派）↑の文章は個人の見解です

ちなみにbottom typeのneverもいる

これを分けるのも、逆に統一するのも面倒なので、サーバー見ながらeslintを調整してもいいかも。

2021-03-23 09:11 UTC, HosokawaR commented on src/usecases/addCourseByManual.ts
> +    return false;
結論としてはここは`void 0`でいいのでしょうか？また、
> void 0はundefinedと同じだか、voidを返すときに利用するのはいいかも

「voidを返すときに利用するのはいい」の意味が汲み取れませんでした… `void` == `undefined` なのになぜ`void`を返すときには利用していいのでしょうか？

2021-03-24 04:21 UTC, HikaruEgashira commented on src/usecases/addCourseByManual.ts
> +    return false;
> 結論としてはここはvoid 0でいいのでしょうか？

:ok:

> void == undefined なのになぜ「voidを返すとき」には利用していいのでしょうか？

1. void 0 読みにくくて、書き方の選択肢が増えるので、できるだけ減らしたいモチベ
2. 型の一致が気になる人もいると思うので void 0 は場合によって使ってもいいよ
3. 文字数を減らすために undefined を void 0 にするといった理由だと分かりにくくなると感じたので利用を限定して書きました

2021-03-24 04:24 UTC, HikaruEgashira approved these changes
お疲れ様ー

2021-03-24 11:31 UTC, merged