CSV 追加のロジックを作成
twin-te/twinte-front pull request #268
Opened 2021-03-22 12:02 UTC by HosokawaR

- 現状（もらったCSVにかかれている講義番号をN回検索）＋（講義番号をM回登録） の通信が発生しています。
- 通信回数の削減はAPIの仕様を変更しないとどうにもできない…と思ったのですがどうでしょう？
- 授業の重複表示等は別のPRでまとめます。

fix: #253

2021-03-23 00:39 UTC, HikaruEgashira requested changes
いい感じー
年度などはAPIから楽器情報と一緒に取得できるようになる仕様の予定だった気がするので、それをstoreに保存してそこの情報を利用する、処理をすると思うので他PRで実装まで待つ感じかな

2021-03-23 00:39 UTC, HikaruEgashira commented on src/components/InputButtonFile.vue
> +      fileName.value = typeof file !== "undefined" ? file.name : "";
```suggestion
      fileName.value = file?.name ?? "";
```

2021-03-24 04:27 UTC, HikaruEgashira requested changes
@SIY1121 複数追加の把握だけ :pray:

2021-03-24 05:01 UTC, SIY1121 reviewed
バッチ系のAPIはこれから追加します

2021-03-24 10:10 UTC, HosokawaR commented
@HikaruEgashira  先輩
そういえば `bulkAddCourseById` とはどういう意図でつけた名前ですか？
`bulk`は名詞で「容量」、形容詞で「巨大な」、動詞で「大きくなる」などの意味ですがなぜこの後に動詞の`addCourseById`が続くのが気になりました。慣例的にこのような命名があるのでしょうか？
あまり名前にこだわっても仕方がないのですが、気になってしまい汗

2021-03-24 12:26 UTC, HikaruEgashira commented
一括という意味でDB保存などで使われる単語（bulk insert）を意識した笑

2021-03-24 13:45 UTC, HosokawaR commented
Bulk insert は初耳でした！insert とよりも inserting な気もしましたが、調べたら bulk insert ででてきますね。英語は難しいです。ありがとうございます。

2021-03-24 17:04 UTC, SIY1121 commented
バッチ系のAPI追加しました

```
course-service:0.1.1
api-gateway:0.5.0
```

で動きます

詳細はopenapi-specと
https://github.com/twin-te/api-gateway/releases/tag/0.5.0
を参照してください

2021-03-25 03:28 UTC, HikaruEgashira commented
@HosokawaR 最新のバッチのやつに修正お願いします！:pray:

2021-03-25 18:19 UTC, HosokawaR commented on .gitmodules
> +	branch = master
submodule を最新の master ブランチに追従するように変更しました。
参考: https://qiita.com/noraworld/items/89ad0faefb048eda0870

2021-03-25 18:27 UTC, HosokawaR commented on src/usecases/index.ts
> +      paramsSerializer: (r) => qs.stringify(r),
`paramsSerializer` に [qs](https://github.com/ljharb/qs) を指定しました。`paramsSerializer`はJSオブジェクトをURLのリクエスト形式に変換するものです。これを入れた理由は`axios`がデフォルトだと、講義コードの複数検索（`codes=XXXXXX,XXXXX...`）に使うコンマがURLエンコードされないからです。（URLエンコードしないと API がエンコードしろと怒ります。）もし `codes.join('%2C')`のように設定しても今度は`%`がエンコードされて`XXXXXX%252CXXXXXX`みたいになってしまうのでこれを導入しました。

2021-03-25 18:35 UTC, HosokawaR commented on src/usecases/index.ts
> +      paramsSerializer: (r) => qs.stringify(r),
バックエンドで`,`も認識してもらうように変更してもらうことも可能かもしれませんが、[RFC3986](https://triple-underscore.github.io/rfc-others/RFC3986-ja.html#section-2.2) によれば
> URI 構成要素についてのデータがデリミタとして予約されている文字の目的と競合する場合、競合するデータは URI が形成される前にパーセントエンコーディングされなければならない。

とあるのでこのようにするのがベストかもしれません。デリミタの定義がよく分かりませんがw

2021-03-26 07:14 UTC, HikaruEgashira requested changes
csvの動作確認でエラー出たので確認してもらえますか？

2021-03-26 07:14 UTC, HikaruEgashira commented on src/usecases/readCSV.ts
> +    reader.readAsText(file);
Blob入るところでFileが入っててエラーでてるかも

![image](https://user-images.githubusercontent.com/39324739/112595762-343df100-8e4e-11eb-8558-5bb94bec2a43.png)

2021-03-26 07:14 UTC, HikaruEgashira commented on src/usecases/bulkAddCourseById.ts
> +        code: v,
```suggestion
      body: codes.map((code) => ({
        code,
```

2021-03-26 07:22 UTC, HosokawaR commented on src/usecases/readCSV.ts
> +    reader.readAsText(file);
windows10 の chrome だと正常に動くのですが…調べてみます。
先輩の環境を教えていただいてもよろしいでしょうか？
![image](https://user-images.githubusercontent.com/45098934/112596468-36547f80-8e4f-11eb-9ae3-59e7d4088419.png)

2021-03-26 07:25 UTC, HikaruEgashira commented on src/usecases/readCSV.ts
> +    reader.readAsText(file);
同じやわ笑
いま確認中です

2021-03-26 07:27 UTC, HikaruEgashira commented on src/usecases/readCSV.ts
> +    reader.readAsText(file);
読み込めた！

2021-03-26 07:27 UTC, HikaruEgashira approved these changes

2021-03-26 07:28 UTC, HosokawaR commented on src/usecases/readCSV.ts
> +    reader.readAsText(file);
先ほどのエラーの原因は判明したでしょうか？

2021-03-26 07:31 UTC, SIY1121 reviewed
courses一括取得のAPIは、見つからない講義があっても結果に含まれないだけでエラーにはならないようにしてるんだけど、無効な科目番号が入ってたときの処理ってどうなってますか？

2021-03-26 07:32 UTC, HikaruEgashira commented on src/usecases/readCSV.ts
> +    reader.readAsText(file);
再現できないので一応無視します。
できればファイル入力を`.csv`のみにするやつも含めたいな
htmlに`accept: 'text/csv, .csv'`

2021-03-26 07:33 UTC, SIY1121 commented on src/usecases/readCSV.ts
> +    reader.readAsText(file);
AndroidWebViewでファイル選択するとき、 `text/csv` だとOKなんだけど、`.csv`だとエラーで落ちたので拡張子の方は含めないでもらえると 🙏

2021-03-26 07:34 UTC, HosokawaR commented
このように有効な講義だけが表示される感じになっています。
「xxx」という講義番号は見つかりませんでした。みたいなメッセージがあると親切ですね…
![image](https://user-images.githubusercontent.com/45098934/112597879-1aea7400-8e51-11eb-8c66-e4daf659591f.png)

2021-03-26 07:36 UTC, SIY1121 commented
無効な科目番号もpostしちゃうと全体が追加失敗しちゃうのが気がかりだっただけなので
見つからなかった科目番号除外してくれてるなら大丈夫です 👍

2021-03-26 07:38 UTC, HosokawaR commented on src/usecases/readCSV.ts
> +    reader.readAsText(file);
わかりました。とりあえず `text/csv' のみ実装します。ここらへんは windwos / macOS / iOS / Android あたりで一度テストしたほうが良さそうですね。

2021-03-26 08:04 UTC, HosokawaR commented on src/usecases/readCSV.ts
> +    reader.readAsText(file);
実装しました、が… windwos だと `text/csv` は機能しないみたいですね。`.csv` だとうまく動くのですが

2021-03-26 08:16 UTC, merged