検索ロジックを追加
twin-te/twinte-front pull request #273
Opened 2021-03-26 09:46 UTC by HosokawaR

重複検知、エラー処理等はこのブランチが merge されたらまとめて実装します。

2021-03-26 09:49 UTC, HosokawaR commented on src/usecases/searchCourse.ts
> +  return timetable as SearchCourseTimetableQuery;
いい方法が思いつかなかったのですが、ここをもっと型安全にしたい気持ちがあります。

2021-03-26 14:03 UTC, SIY1121 commented on src/usecases/searchCourse.ts
> +  return timetable as SearchCourseTimetableQuery;
specでは`SearchCourseTimetableQuery`内のフィールドは全部optionalなので
```typescript
const timetable: SearchCourseTimetableQuery = {};
```
で行けるはずだから `openapi2aspida` が変な型生成してそう
（おそらく全部optionalだと全部requreidの型を生成してしまってる感）

2021-03-26 14:09 UTC, SIY1121 commented on src/usecases/searchCourse.ts
> +  return timetable as SearchCourseTimetableQuery;
ここが原因っぽい気がする
https://github.com/aspida/openapi2aspida/blob/1619112f38f5824afffcf1fbd92b91f3998cbd24/src/builderUtils/converters.ts#L62

2021-03-26 15:10 UTC, SIY1121 commented on src/usecases/searchCourse.ts
> +  return timetable as SearchCourseTimetableQuery;
issue投げてみた
とりあえずこのままか、型の方をoptionalに書き替えるで良さそう

2021-03-26 15:14 UTC, HosokawaR commented on src/usecases/searchCourse.ts
> +  return timetable as SearchCourseTimetableQuery;
issue まで投げて頂きありがとうございます！
とりあえず現状は書き換えて対応したいと思います。

2021-03-27 00:14 UTC, HikaruEgashira requested changes
シンプルで良かった！処理部分はこれでいいかも
true, false周りは消したほうが可読性上がるので修正お願いします:pray:

2021-03-27 00:14 UTC, HikaruEgashira commented on src/usecases/searchCourse.ts
> +  });
```suggestion
  return schedules.some(
    (schedule) =>
      schedule.modules.includes(module) &&
      schedule.days.includes(day) &&
      schedule.periods.includes(String(period))
  );
```

2021-03-27 00:14 UTC, HikaruEgashira commented on src/usecases/searchCourse.ts
> +        ),
```suggestion
        timetable: schedulesToTimetable(schedules.map(parseSchedules)),
```

2021-03-27 08:15 UTC, HosokawaR commented on src/usecases/searchCourse.ts
> +        ),
言われてみればこんな書き方ができますね…！

2021-03-27 11:41 UTC, HikaruEgashira approved these changes
ナイス！

2021-03-27 12:38 UTC, merged