add 時間割の時限に授業開始時刻と終了時刻を表示
twin-te/twinte-front pull request #354
Opened 2021-04-04 02:57 UTC by hayato24s

・vuexにtableTimeModeを追加
・useTableTimeModeの追加（ローカルストレージで管理）
・index.vueで授業の時刻を表示できるように
・view-settings.vueで切り替えができるように

2021-04-04 05:14 UTC, KanadeNishizawa requested changes
![Videotogif (1)](https://user-images.githubusercontent.com/48097323/113499071-e449e300-954d-11eb-9288-ccf71065fd0b.gif)
画面の縦幅が低い時に、この時限表示がはみ出た分時間割全体がスクロールしてしまうのが気になりました。
昨日、科目のtileで最初に修正してくれていたのと同じように、はみ出す場合はタイル内だけでスクロールするようにお願いします:pray:

タイル内スクロールについて、科目はダメなのに時限は良い理由は、
- 科目とは違い、時限のはみ出しは主要な端末(スマホ、タブレット、PCの通常のウィンドウサイズ)では起こらない現象だから
- 科目タイルはタップでもイベントが起きたのでスクロールはミスタップを誘発する恐れがあったが、時限はタップ判定になってしまっても何も起こらないから

です!

2021-04-04 06:37 UTC, HikaruEgashira requested changes
ありがとう！コメント部分だけ↓

2021-04-04 06:37 UTC, HikaruEgashira commented on src/store/index.ts
> +  tableTimeMode: Boolean;
名称は変えていいけどbooleanだとわからないので変更お願いします
localstrageで使う値もここで利用する文字列で
```suggestion
  tableTimeMode: "default" | "special";
```

2021-04-04 07:04 UTC, hayato24s commented on src/store/index.ts
> +  tableTimeMode: Boolean;
大学院生用と同じようなかんじをイメージしてbooleanにしてみたのですがどうでしょうか？

<img width="477" alt="スクリーンショット 2021-04-04 16 02 44" src="https://user-images.githubusercontent.com/68944024/113501342-3e9f6f80-955f-11eb-8f41-c735d53409bf.png">

2021-04-04 07:13 UTC, HikaruEgashira commented on src/store/index.ts
> +  tableTimeMode: Boolean;
なんか違うの見てたわ
オッケーですあと`boolean`

2021-04-04 07:43 UTC, hayato24s commented
スクロールがうまくできないのでやってもらいたいです。
@KanadeNishizawa

2021-04-04 08:42 UTC, KanadeNishizawa commented
わたし今日明日は時間が厳しいので別の方にパスしてください！

2021-04-04 11:20 UTC, HikaruEgashira requested changes

2021-04-04 11:20 UTC, HikaruEgashira commented on src/store/index.ts
> +  tableTimeMode: false,
こっちにしときたい
```suggestion
  tableTimeMode: true,
```

2021-04-04 11:32 UTC, HikaruEgashira approved these changes
@hayato24s 
デフォルトをtrueにしたかったけど、そうなるとモードオフの意味がほぼ無くなるので、falseにした

2021-04-04 12:27 UTC, KanadeNishizawa requested changes

2021-04-04 12:27 UTC, KanadeNishizawa commented on src/pages/index.vue
> +    gap: $spacing-1;
flexに対するgapプロパティはSafariで対応していないので使わないで欲しいです…!

2021-04-04 12:27 UTC, KanadeNishizawa commented on src/pages/index.vue
> +      overflow-y: auto;
```suggestion
      overflow-y: auto;
```
paddingがない

2021-04-04 12:37 UTC, KanadeNishizawa requested changes

2021-04-04 12:37 UTC, KanadeNishizawa commented on src/pages/index.vue
> +    font-size: 0.9rem;
あとこのcolorは$text-sub-lightです
<img width="518" alt="スクリーンショット 2021-04-04 21 36 50" src="https://user-images.githubusercontent.com/48097323/113508948-e338a600-958d-11eb-8768-ae8e72dee59a.png">

2021-04-04 12:42 UTC, KanadeNishizawa commented
おそらく早めにデプロイしたいものだと思うので、上記のものを修正して、追加修正してくれたスクロールに副作用が出ないことを確認できたらmergeしちゃってください

2021-04-04 12:46 UTC, hayato24s commented
僕なぜか、このブランチだけ
`GET http://localhost:3000/node_modules/.vite/chunk.XBGIHFAI.js?v=48b6cce2 net::ERR_ABORTED 404 (Not Found)`
のエラーが出ていてできないので代わりにやっていただけると🙏
@HikaruEgashira

2021-04-05 08:07 UTC, KanadeNishizawa approved these changes

2021-04-05 12:34 UTC, merged