fix entity/day
twin-te/twinte-front pull request #373
Opened 2021-04-04 13:28 UTC by hayato24s

- weekday（平日）には土日を含まない。
- 基本は、英語表記の型は Day を用いる。（他の英語表記の型を作るとややこしくなるため）

動かなくなっているページがあるかもしれないので確認お願いします。

2021-04-04 13:38 UTC, hayato24s commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
```suggestion
export const jaToDay = (day: string): Day =>
  week.find((key) => weekMap[key] === day) ?? "Unknown";
```
にすべき？？

2021-04-04 13:40 UTC, hayato24s commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
それとも、`scheduleJaToDay`なるものを新しく作るべき？

2021-04-04 13:45 UTC, HosokawaR commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
それは型の安全を捨てているので良くないと思う。

2021-04-04 13:50 UTC, hayato24s commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
```
export type ScheduleDayJa = DayJa | NotWeekDay | "指定なし";

export const scheduleJaToDay = (day: ScheduleDayJa): Day =>
  week.find((key) => weekMap[key] === day) ?? "Unknown";
```
これでどう？

2021-04-04 13:53 UTC, HosokawaR commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
`Unknown` ? `Unknown` が来るのは型的におかしいような気もしたんだが、どうだろう

2021-04-04 14:00 UTC, hayato24s commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
`Day`に`Unknown`は含まれるよ
あと、これはlintでエラーが起きている箇所を参考に作った。

2021-04-04 14:01 UTC, HosokawaR commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
`key` は `scheduelDayJa` になってる？

2021-04-04 14:04 UTC, HosokawaR commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
あーいやこれでいいのか…？でも scheduleDayJa から Unknown は生まれないと思ったのだが。typescript の型システムはそこまで推論してくれないのか

2021-04-04 14:06 UTC, HosokawaR commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
でもちょっと徹夜気味なので、明日朝起きて僕も考えます。push してもらえると嬉しい。

2021-04-04 14:28 UTC, hayato24s commented on src/entities/day.ts
> +  week.find((key) => weekMap[key] === day) ?? "Unknown";
```
week: Day[];
NotWeekDay = "その他";
ScheduleDayJa = DayJa | NotWeekDay | "指定なし";
weekMap: { [key in Day]?: DayJa };

export const scheduleJaToDay = (ja: ScheduleDayJa): Day =>
  week.find((key) => weekMap[key] === ja) ?? "Unknown";
```

keyは`Day`だね

2021-04-04 23:39 UTC, HosokawaR approved these changes
余裕があるなら
```
export type WeekDay = Extract<
  Day,
  "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun"
>;
export type WeekdayDay = Extract<Day, "Mon" | "Tue" | "Wed" | "Thu" | "Fri">;
export type WeekendDay = Exclude<WeekDay, WeekdayDay>;
export type SpecialDay = Extract<Day, "Intensive" | "Appointment" | "AnyTime">;

export type WeekDayJa = "月" | "火" | "水" | "木" | "金";
export type DayJa = "月" | "火" | "水" | "木" | "金" | "土" | "日";
export type NotWeekDay = "その他";
export type ScheduleDayJa = DayJa | NotWeekDay | "指定なし";
export type SpecialDayJa = "集中" | "応談" | "随時";
```
手打ちではなく、このように API の `Day` との型の部分構造を明示したり、引き数のそれぞれ `Day` ではなく、上のようなもっと範囲を限定した型のほうが安全かなと思いました。
`Extract` を使うことによる部分構造の明示は、api の定義が変更になったとき、あるいは typo したときにすぐに型エラーで検知できたりといったメリットがあります。

ただいまはバグ修正が優先事項なので、ここらへんの安定性は後回しでいいと思うので Approve しました。

2021-04-04 23:45 UTC, HosokawaR commented on src/entities/day.ts
> + * 基本は、英語表記の型は Day を用いる。（他の英語表記の型を作るとややこしくなるため）
この意見は僕も賛成なのですが、一つ注意したいのが

- weekday は月～金
- weekend は土日
- week は weekday + weekend

となっており、Day をつけるルールを付ける場合

- weekday → weekdayDay
- weekend → weekendDay
- week      → weekDay

となり分かりづらいのが辛いところです。もう weekDay1 weekDay2 weekDay3 とかじゃまずいかな…

2021-04-05 00:17 UTC, hayato24s commented
> 余裕があるなら
> 
> ```
> export type WeekDay = Extract<
>   Day,
>   "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun"
> >;
> export type WeekdayDay = Extract<Day, "Mon" | "Tue" | "Wed" | "Thu" | "Fri">;
> export type WeekendDay = Exclude<WeekDay, WeekdayDay>;
> export type SpecialDay = Extract<Day, "Intensive" | "Appointment" | "AnyTime">;
> 
> export type WeekDayJa = "月" | "火" | "水" | "木" | "金";
> export type DayJa = "月" | "火" | "水" | "木" | "金" | "土" | "日";
> export type NotWeekDay = "その他";
> export type ScheduleDayJa = DayJa | NotWeekDay | "指定なし";
> export type SpecialDayJa = "集中" | "応談" | "随時";
> ```
> 
> 手打ちではなく、このように API の `Day` との型の部分構造を明示したり、引き数のそれぞれ `Day` ではなく、上のようなもっと範囲を限定した型のほうが安全かなと思いました。
> `Extract` を使うことによる部分構造の明示は、api の定義が変更になったとき、あるいは typo したときにすぐに型エラーで検知できたりといったメリットがあります。
> 
> ただいまはバグ修正が優先事項なので、ここらへんの安定性は後回しでいいと思うので Approve しました。

僕もこっちの方が安全かなと思ったのですが、修正しなくてはならないコードが一気に増えそうなのでやめました。でも、修正するなら後回しにするのではなく今行ったほうがよさそう？

2021-04-05 01:48 UTC, HosokawaR commented
やってくれると嬉しいが、労力がかかるなら無理はしないで他のバグ fix に労力を費やしてもいい、と思っています。

2021-04-05 04:33 UTC, HikaruEgashira requested changes
書き方が統一してていいんじゃないだろうか:+1:
Recordへの変更もお願いしたいです

2021-04-05 04:33 UTC, HikaruEgashira commented on src/entities/day.ts
> +export const weekMap: { [key in Day]?: DayJa } = {
```suggestion
export const weekMap: Record<Day, DayJa> = {
```

2021-04-05 04:34 UTC, HikaruEgashira commented on src/entities/day.ts
> +export const weekMap: { [key in Day]?: DayJa } = {
`?`がなければRecordのみに

2021-04-05 13:12 UTC, HosokawaR commented on src/entities/day.ts
> +export const weekDayToJa = (day: Day): WeekDayJa => weekdayMap[day] ?? "月";
```suggestion
export const dayToJa = (day: Exclude<Day, "unknown">): WeekDayJa => weekdayMap[day] ?? specialDayMap[day];
```
これで scpecialDay にも対応できると思われる。微妙にまちがっていたらごめん。

2021-04-05 13:13 UTC, hayato24s commented on src/entities/day.ts
> +export const weekDayToJa = (day: Day): WeekDayJa => weekdayMap[day] ?? "月";
さっきfullDayJaToDayを作った。

2021-04-05 13:17 UTC, HosokawaR commented on src/entities/day.ts
> +export const weekDayToJa = (day: Day): WeekDayJa => weekdayMap[day] ?? "月";
ああ、dayToJa の `day` って月～日か。紛らわしい。api.ts の `Day` かと思った。

2021-04-06 08:59 UTC, HikaruEgashira approved these changes

2021-04-06 12:16 UTC, merged