fix 2019年度を選択できるように
twin-te/twinte-front pull request #375
Opened 2021-04-04 14:18 UTC by hayato24s

ドロップダウンを少し変更したので確認お願いします。

2021-04-04 15:23 UTC, KanadeNishizawa requested changes
「自動」は「指定なし」とは違って意味を持って指定されている項目なので、文字色は他の2021や2020などと同じでお願いします。
(「指定なし」の色が薄いのは初期値だからではなく、ユーザーが意味のある指定を行っていないことを示すため）

2021-04-04 15:41 UTC, hayato24s commented
こうですかね？

<img width="924" alt="スクリーンショット 2021-04-05 0 38 56" src="https://user-images.githubusercontent.com/68944024/113514072-8f3abb00-95a7-11eb-9ef1-9005c2e21571.png">

2021-04-04 16:24 UTC, KanadeNishizawa approved these changes
あざます!

2021-04-05 04:27 UTC, HikaruEgashira approved these changes

2021-04-05 11:11 UTC, HosokawaR approved these changes

2021-04-05 11:15 UTC, merged