PC画面のスクロールを無くした&refactor
twin-te/twinte-front pull request #381
Opened 2021-04-05 07:21 UTC by hayato24s

pc画面でのスクロールを無くした。
極力marginやpaddingを使わずに、gridを使用した。

2021-04-05 07:39 UTC, HikaruEgashira requested changes
最新のverでiphoneX用の変数が追加してるので、 #376 見て追加修正してほしいです！
バグの中でも、このタスクはそこそこゆっくりしてもいいと思います！

2021-04-05 07:39 UTC, HikaruEgashira commented on src/pages/view-settings.vue
> +    height: calc(100vh - 8rem); // header + gap
ここはどういう意図？

2021-04-05 07:39 UTC, HikaruEgashira commented on src/pages/add/index.vue
> +      <div class="main__cards">
```suggestion
      <div class="main__card-group">
```

2021-04-05 07:44 UTC, hayato24s commented on src/pages/view-settings.vue
> +    height: calc(100vh - 8rem); // header + gap
ミスです。

2021-04-05 08:09 UTC, hayato24s commented on src/scss/_mixin.scss
> +}
これでどうでしょう？

2021-04-05 12:29 UTC, HikaruEgashira commented on src/scss/_mixin.scss
> +}
よさげ

2021-04-06 08:09 UTC, hayato24s commented
このPR  -> #347

2021-04-06 08:56 UTC, HikaruEgashira commented on src/pages/add/index.vue
> +      <div class="main__card-group">
ここdivdivなのでsectionやないかな（コメント）

2021-04-06 08:57 UTC, HikaruEgashira approved these changes
re requestしてほしい！

2021-04-06 13:44 UTC, HikaruEgashira approved these changes

2021-04-06 17:47 UTC, HosokawaR commented
#397 と重複

2021-04-07 05:30 UTC, KanadeNishizawa approved these changes
良さげです!

2021-04-07 05:56 UTC, merged