データが不完全なため表示されていなかった授業を表示されるようにした
twin-te/twinte-front pull request #405
Opened 2021-04-07 12:12 UTC by hayato24s

### 変更点
- 日曜授業も表示されるようになった
- その他は表示されていない講義がある場合のみ表示される
- その他では他の場所で表示されていない講義が表示される
- 特殊授業のscheduleが勝手に変更されるバグの修正をした
- CourseToSpecialTableを修正した

<img width="380" alt="スクリーンショット 2021-04-07 21 03 27" src="https://user-images.githubusercontent.com/68944024/113863531-bf22d200-97e4-11eb-926b-26cfb6e3890d.png">
<img width="380" alt="スクリーンショット 2021-04-07 20 58 20" src="https://user-images.githubusercontent.com/68944024/113863301-75d28280-97e4-11eb-9c93-539ef4e45e31.png">

2021-04-08 04:27 UTC, HikaruEgashira requested changes
ある程度読めたのでプログラミング力向上してる気がする。（主観）
関数には`@example`や`input outputの説明`などのjsDoc入れてもらえるとありがたいです！

2021-04-08 04:27 UTC, HikaruEgashira commented on src/entities/module.ts
> +        return moduleFlg[0 + i] ? a + ["A", "B", "C"][i] : a;
0いらなくない？

2021-04-08 04:27 UTC, HikaruEgashira commented on src/usecases/courseListToSpecialTable.ts
> +    { [key in SpecialDay | "Weekend"]: RegisteredCourse[] }
```suggestion
    Record<SpecialDay | "Weekend", RegisteredCourse[]>
```

2021-04-08 07:04 UTC, KanadeNishizawa reviewed
styleの変更に関して、iOS Safariで大丈夫な確証が欲しいです。
もし急ぎでmergeしたければ元のstyleのままで:pray:

2021-04-08 07:04 UTC, KanadeNishizawa commented on src/pages/index.vue
> +  display: grid;
例のiOS Safariにおけるgridの表示崩れが怖いので、件の調査と検証が済んでから適用したい気分です。
（何で崩れるか今のところはっきりしていないので、判明するまでは極力変えたくない)

2021-04-09 04:38 UTC, hayato24s commented
### 変更点
- 今まではtableで現在のモジュールの講義しか持っていなかったが春秋ABC全てのモジュールの講義を持つようにした
- 大学院生モードの時のみ7,8限を表示するようにした。院生モードoffの時に7,8限が登録された場合は特殊のその他の欄に表示

2021-04-09 04:41 UTC, HikaruEgashira commented on src/pages/index.vue
> +        <template v-if="undisplayedCourses.length !== 0">
これ前までエラー起きてたけど治ってそうやね

2021-04-09 04:46 UTC, HikaruEgashira approved these changes
オッケーです:sparkle:

2021-04-09 04:58 UTC, HikaruEgashira commented on src/pages/index.vue
> +  display: grid;
> 例のiOS Safariにおけるgridの表示崩れ

が何をさしているのかが分からない

2021-04-09 05:11 UTC, KanadeNishizawa commented on src/pages/index.vue
> +  display: grid;
https://github.com/twin-te/twinte-front/issues/407

https://twinte.slack.com/archives/CNEUKN7QX/p1617804477057700?thread_ts=1617803521.045800&cid=CNEUKN7QX

2021-04-09 05:16 UTC, HosokawaR commented on src/pages/index.vue
> +  display: grid;
僕の方から軽く経緯をを説明します。
#381  #397 にて `mergin` や `padding` で適当な値に設定していた css を grid に書き換えました。その後西沢先輩がダークモードを追加し、デプロイしたところフィードバックや Twitter にて時間割が見切れて見れない、ヘッダーに文字が重なっているなどのバグ報告が多数ありました。
原因を調べたところ、iOS の webView で grid の設定がうまく機能してないだろうということがわかりました。gird-gap や無名 gird-area （`"sidebar ..."` の `...` です。）当日は #381 #397 を revert して対応しました。
その後、再発防止のために西沢先輩と宍戸くんと僕で、デプロイ前は実機の iPhone で css 崩れがないか確認しよう、ということになりました。（ たこなす先輩に聞いたところ macOS の safari ≠ iOS の safari = webView だそうです。）
しかし実機テストをするためには「iPhone」 CORS を解除する必要があるためバックエンドに `Access-Control-Allow-Origin: *` をつけてもらうのを待っています。

2021-04-09 14:41 UTC, KanadeNishizawa approved these changes

2021-04-09 14:47 UTC, merged