Add tag components
twin-te/twinte-front pull request #475
Opened 2022-03-21 07:04 UTC by hayato24s

### やったこと
- タグ関連のコンポーネントを追加しました。
- `/tag-develop`で確認できます。
- ドラッグアンドドロップは丸2日かけてもうまくできなかったため、とりあえず諦めました。
- コンポーネントの`Button`・`Dropdown`・`IconButton`に`disabled`を追加しました。

### 備考
- コンポーネントの細かな挙動などは別PRで確認したいと思っています。

2022-03-21 09:03 UTC, HikaruEgashira approved these changes
CreditFilterがOrganismになってるからもうちょい関心を減らした方がよさそう
このあたりはリファクタリングするときで！

2022-03-22 06:55 UTC, KanadeNishizawa requested changes
ウオオお疲れ様でした! 1箇所だけ確認お願いします。

2022-03-22 06:55 UTC, KanadeNishizawa commented on src/components/CreditCourseListContent.vue
> +    font-weight: 500;
```suggestion
    font-weight: 500;
    line-height: $multi-line;
```

2022-03-22 06:55 UTC, KanadeNishizawa commented on src/components/CreditCourseListContent.vue
> +    font-weight: 500;
授業名は複数行になる可能性があるので

2022-03-22 10:58 UTC, hayato24s commented on src/components/CreditCourseListContent.vue
> +    font-weight: 500;
修正しました！

2022-03-22 11:18 UTC, KanadeNishizawa approved these changes
あざます!

2022-03-22 11:37 UTC, merged