Add credit
twin-te/twinte-front pull request #476
Opened 2022-03-21 11:27 UTC by hayato24s

### やったこと
- 単位数のページを追加しました。
- `/credit`から確認できます。
- tag関連の`entity`の整理も行いました。

### 備考
- Figma ではわかりにくい細かな挙動などもこのPRで確認したいです。
- ローカル環境でも動くようになっているので確認していただきたいです。

### ファイルの説明
- `src/usecases/dummyRepo.ts` -> api や vuex の代わりです。後で消します。
- `src/usecases/creditPageFunctions.ts` -> `src/pages/credit` で使用する処理を書いています。
- `src/pages/credit.ts` -> 単位数のページ

2022-03-22 05:21 UTC, HikaruEgashira requested changes
挙動よさげ～

2022-03-22 05:21 UTC, HikaruEgashira commented on src/pages/credit.vue
> +      () => mode.value,
refはそのまま引数におけるはず
https://v3.ja.vuejs.org/api/computed-watch-api.html#watch

```suggestion
      mode,
```

2022-03-22 12:13 UTC, KanadeNishizawa requested changes
branch/add-tag-componentの時点では".tag-list-content__container--selected"へ
"box-shadow: $shadow-primary-concave;"が設定してあったようですが、どこかのタイミングで消えちゃってるみたいなので復元してもらえると!

以上2点だけお願いします!

2022-03-22 12:13 UTC, KanadeNishizawa commented on src/pages/credit.vue
> +  <div class="credit">
コンテンツ部分に他のページ(eg.授業追加、フィードバック)と同じ値でmax-width設定してあると嬉しいです!

2022-03-23 07:03 UTC, hayato24s commented
修正しました！

タグの順番を変えるためのドラッグアンドドロップの実装と、タグの削除モーダルは別PRでやります。

2022-03-23 08:05 UTC, KanadeNishizawa approved these changes
スーパー便利機能〜〜
あざます!

2022-03-24 01:00 UTC, HikaruEgashira approved these changes
いいかんじ～

2022-03-24 03:13 UTC, HosokawaR approved these changes
お疲れさまです！

2022-03-24 04:19 UTC, merged