Add drag and drop
twin-te/twinte-front pull request #478
Opened 2022-03-24 14:14 UTC by hayato24s

### Done
- `updateReactiveTags` のバグの修正
- タグの順番を変更するためのドラッグアンドロップの追加
- タグ削除時のモーダルの追加
- サイドバーに`単位数`を追加
- ドロップダウンが閉じないバグの修正
- `CreditCourseListContent`の細かい挙動の修正

2022-03-25 16:34 UTC, HikaruEgashira approved these changes
sortablejsなのでうれしい！
こっちのほうが見やすくない？ってとこだけサジェストいれたけどどうだろう？

2022-03-25 16:34 UTC, HikaruEgashira commented on src/usecases/creditPageFunctions.ts
> +  newTags.forEach((tag) => reactiveTags.push(tag));
ここループするの損な感じする

```suggestion
  reactiveTags = [...reactiveTags, ...newTags];
```

2022-03-26 01:37 UTC, hayato24s commented on src/usecases/creditPageFunctions.ts
> +  newTags.forEach((tag) => reactiveTags.push(tag));
スプレッド構文で配列の変更がビューに反映されるかはわかりません。
配列のリアクティビティが保証されているのは以下のメソッドのみらしいので、`push`を使用しています。
- push()
- pop()
- shift()
- unshift()
- splice()
- sort()
- reverse()

https://jp.vuejs.org/v2/guide/list.html

for文を使わない書き方では`splice`を使う感じになるでしょうか。
```suggestion
  reactiveTags.splice(reactivetags.length, 0, ...newTags);
```

2022-03-26 01:37 UTC, hayato24s commented on src/usecases/creditPageFunctions.ts
> +  );
アルゴリズムとかはあまりわからないのですが、Objectを毎回生成するよりは1度だけ生成するようにした方がいいのかなという感じです。改行が多くて少し見にくいですが。

2022-03-26 02:02 UTC, HosokawaR commented on src/usecases/creditPageFunctions.ts
> +  newTags.forEach((tag) => reactiveTags.push(tag));
そもそもなのですが layered architecture っぽい雰囲気で作られている Twinte-front において usecase が presentaion 層の問題である reactive に対して関心があるということが物事を難しくしている感があります。
ここらへんは一度しっかり決めてもいいのかもしれませんね。

※これはコードを変えてほしいという意図ではありません。これを気にしっかりアーキテクチャをチーム内で話したほうがいいかもねという提案です。

2022-03-26 03:25 UTC, hayato24s commented on src/usecases/creditPageFunctions.ts
> +  newTags.forEach((tag) => reactiveTags.push(tag));
`usecases/creditPageFunctions.ts`内にある`updateReactiveTags`と`updateCreditCourseWithStateList`は `reactive()`な値の変更を行うための処理なので、presentaion 層の`pages/credit.vue`に戻した方がわかりやすそうですね。

2022-03-26 03:31 UTC, hayato24s commented on src/usecases/creditPageFunctions.ts
> +  newTags.forEach((tag) => reactiveTags.push(tag));
アーキテクチャ関連の話で、
- `entity` でapi関連の型を用いた処理は書きたくない
- twinte-front における`usecase`の役割が曖昧 

だなと思っていた次第です。

2022-03-26 03:32 UTC, HosokawaR commented on src/usecases/creditPageFunctions.ts
> +  newTags.forEach((tag) => reactiveTags.push(tag));
たしかにそうかもしれませんね。
ただこの場で即時直すべきというよりかは、このようなアーキテクチャの不整合があることは理解しつつ、今回は merge して、別の機会でしっかり話し合ってリファクタリングするとかでもいいと思います…！

reactive 意外にも DIP（依存性逆転の原則）とか entitiy の責務とかいろいろチーム内で考えたいな～と思うことがあり、この場で全て解決するのは難しいので。

2022-03-26 05:11 UTC, KanadeNishizawa approved these changes
FOOOOOOO↑↑↑

2022-03-26 05:13 UTC, HosokawaR approved these changes
お疲れさまです！
コメントの通り細かい部分は後ほどリファクタリングで良いと思う＆リリース速度も大事派なので Approve させていただきます。

2022-03-26 05:17 UTC, KanadeNishizawa requested changes
すみませんnot appでした、TagEditorのpaddingがないのでそこだけ追加お願いします!

2022-03-26 05:58 UTC, HosokawaR commented on src/usecases/creditPageFunctions.ts
> +  );
> アルゴリズムとかはあまりわからないのですが、Objectを毎回生成するよりは1度だけ生成するようにした方がいいのかなという感じです。



たしかにパフォーマンス的にはスプレッド構文を使うやり方よりも @hayato24s のやり方のほうが良いかもしれません。しかし個人的には以下の理由よりスプレッド構文のほうが良いかなと考えております。


1. 無視できるほどのパフォーマンス上の改善である
タグは多くて 10^2 程度だと思われ、この程度の量ならほぼ誤差だと思われます。現代のデバイスにおいては無視してよい差だと。

2. 統一性を失う
他の箇所でもスプレッド構文を多用しているのでそことの統一性を失うと思います。（なぜ統一性が大事なのだといわれると説明が難しいですが…）

3. 宣言的ではないので少々わかりにくい
これはかなり個人的な意見ですが…
`({ ...idToOrder, [tag.id]: i })`のほうが宣言的でどのようなオブジェクトが返されるのかが直感的で読みやすいかと思われます…

4. この書き方で実行されるとは限らない
そもそもな話ですが TypeScript はトランスパイルされ JavaScirpt となり最適化される可能性があり、出力ターゲットによってはここで書いたものがそのまま実行されるとは限りません。
特に手元の環境では
```ts
  console.log("Here !");
  const idToOrder = compCommonTags.reduce<Record<string, number>>(
    (idToOrder, tag, i) => ({
      ...idToOrder,
      [tag.id] : i
    }),
    {}
  );
```
が
```ts
    console.log("Here !");
    const r = d.reduce((e, t, a) => s(s({}, e), { [t.id]: a }), {});
    e.sort((e, t) => r[e.id] - r[t.id]),
      e.forEach((e, t) => {
        const a = d[t];
        (e.name = a.name),
          rc(e) && rc(a) && (e.credit = a.credit),
          cc(e) && cc(a) && (e.assign = a.assign);
      });
    t.filter((e) => n.includes(e.id)).forEach((t) => e.push(t));
```
にトランスパイルされる模様です。
このような記法上のパフォーマンスはコンパイラに前任するのも手だと思います。


主観多めなのでご意見ぐださい。

2022-03-26 08:37 UTC, HikaruEgashira commented on src/usecases/creditPageFunctions.ts
> +  newTags.forEach((tag) => reactiveTags.push(tag));
想定のアーキテクチャとしては、

- usecaseはフレームワーク非依存
- リアクティブなやつはhooksに置く

あたりが想定だった。
機能追加終わったらアーキテクチャのドキュメント化も含めてチーム内で話し合おう！

2022-03-26 08:52 UTC, HikaruEgashira commented on src/usecases/creditPageFunctions.ts
> +  );
自分の意見としては、
チーム開発においては、コード最適化はランタイムの責務にしちゃって、可読性が高い範囲で宣言的なコードを目指す方針がいいと思う。

逆にアルゴリズムに関してはエンジニアがするしかないので重たくなりそうなユースケースでは気にした方がいいかもしれない。

2022-03-26 12:31 UTC, hayato24s commented
@KanadeNishizawa 
以下の点において修正を行いました。

- `TagEditor`のスペーシングの変更
- スクロールが発生する要素の左右のパディングの追加（スクロールバーで見づらくなってしまうので）
- タグが0個の時の`CourseListContent`の表示

2022-03-26 15:28 UTC, KanadeNishizawa requested changes
確認しました、対応ありがとうございます!

デザインとの差分が少しあったため修正をお願いしたいです…!
- `.filter-all__label`に`  font-weight: 500;`を追加
- `.credit-course-list-content`のリストを囲む`shadow-base`の追加

↓は私のデザインデータのミスで申し訳ないんですが、修正してもらえると助かります…。
- `tag-list-content__name--selected`の`font-size: $font-medium;`を削除

2022-03-26 15:28 UTC, KanadeNishizawa commented on src/components/CreditFilter.vue
> +    padding: $spacing-2 $spacing-2;
> スクロールが発生する要素の左右のパディングの追加（スクロールバーで見づらくなってしまうので）
こちら助かりました! 1点、paddingはスクロールバーが表示される右サイドだけで良さそうです。

```suggestion
    padding: $spacing-2 $spacing-2 $spacing-2 0;
```

2022-03-27 03:09 UTC, hayato24s commented
@KanadeNishizawa 
以下の部分を修正しました。

- `CreditFilter` のスクロール部分の `padding-right` の変更
- `TagListContent` の `credit` の `font-size` を `1.4rem` のままに
- `TagListContent` の `name` の `font-size` を `1.2rem` に変更
- `CourseListContent` と `main__mask` の間に `main_courses` を追加
- `main__courses` に `box-shadow` などを設定

2022-03-27 03:12 UTC, hayato24s commented on src/pages/credit.vue
> +    padding: $spacing-3 $spacing-2;
左右の `padding` ですが どのように設定すればよいでしょうか？
一枚目が`0.8rem` 二枚目が`0`となっています。

<img width="309" alt="スクリーンショット 2022-03-27 11 39 15" src="https://user-images.githubusercontent.com/68944024/160265029-07d95eae-8d4e-47ab-ad3e-cce56c7bb251.png">
<img width="312" alt="スクリーンショット 2022-03-27 11 41 56" src="https://user-images.githubusercontent.com/68944024/160265035-af0e2c75-2f48-472b-acff-951f52996f1f.png">

2022-03-27 03:53 UTC, KanadeNishizawa commented on src/pages/credit.vue
> +    padding: $spacing-3 $spacing-2;
0.8remの方でお願いします!

2022-03-27 03:56 UTC, KanadeNishizawa approved these changes
パーペキです、色々細かい要望など対応してくれてありがとうございました!

2022-03-27 05:57 UTC, merged