Add tag api logic
twin-te/twinte-front pull request #485
Opened 2022-03-29 16:07 UTC by hayato24s

- タグ関連のapiを繋ぎました、動きます。（ほぼ完成です）
- コードはとても汚いのでいつかリファクタリングしたいです。
- デバックをできるだけ多くの方にして頂きたいので、もしお時間がありましたら、お願い致します🙇‍♂️

2022-03-30 03:58 UTC, HikaruEgashira commented on src/pages/credit.vue
> +          registerdCourses.push(...(await getCourseListByYear(ports)(year)));
@SIY1121 これAPI欲しいね（future work）

2022-03-30 04:24 UTC, HikaruEgashira requested changes
動くぞ！
ただタグ順序だけうまくいかないナウ
（ https://twinte.slack.com/archives/CJLJX1G2G/p1648611776551149　のエラーでるアカウントじゃ使えなかったけど）

すぐに対応できそうな箇所だけ↓かいた！

2022-03-30 04:24 UTC, HikaruEgashira commented on src/usecases/creditPageFunctions.ts
> +    if (compTags == undefined) return;
```suggestion
    if (compTags === undefined) return;
```

2022-03-30 04:24 UTC, HikaruEgashira commented on src/templates/Layout.vue
> +    await getCourseListByYear(ports)(await getYear(ports));
これいる？
必要になったときにどうせ呼び出されるので、ここで呼び出す必要性があるかな？

2022-03-30 04:24 UTC, HikaruEgashira commented on src/store/mutations.ts
> +    );
これで代入一回になりそう
```suggestion
    state.courses = state.courses.map(courses => {
      courses.filter(
        (course) => course.id !== id
      )
    });
```

2022-03-30 04:24 UTC, HikaruEgashira commented on src/store/index.ts
> +  courses: Record<number, RegisteredCourse[]>;
これ偉すぎる。numberは年度ってコメントあってもいいかも

2022-03-30 12:23 UTC, SIY1121 approved these changes
並べ替え含めて動作確認できました。お疲れさまです 🎉 

デザインで気になったところをいくつか 🙏 
1. タグでフィルタリングする機能について、タグ名や合計の部分をクリックできることに気づくまで時間がかかったので、ラジオボタン等でクリックできますアピールできると良いかも？（初めて画面を見た時に、やたら合計が強調されてるなと思っただけでボタンだと認識できなかった。）
2. 「開く」「折りたたむ」という言葉のイメージからボタンを押すと、画面の構成がパッと切り替わって視線が迷子になってストレスなので、アニメーションで開閉を表現できると自然に視線誘導できそう
3. （細かいところだけど）「合計」と下のタグの選択を交互に切り替えると「タグごとの単位数」のラベルがガクガク動くのに違和感を感じた

2022-03-30 16:53 UTC, hayato24s commented
- タグの順番を変更するとネットワークエラーが出てきてしまうのは、`PATCH`でCORSに引っかかっているからのようです。拡張機能のデフォルト値に入ってなかったみたいです。
- 修正は明日やります。
- ひとつ気になっているのですが、全体的に画面の更新がワンテンポ遅い感じがします。こういう場合は、apiを叩く前にデータの更新をした方が良いのでしょうか？

2022-03-30 17:14 UTC, KanadeNishizawa reviewed
実装お疲れさまでした!

デザインについて
@SIY1121 @hayato24s 
 
> タグでフィルタリングする機能について...

mtg時にラジオボタン案vs色ネガポジ反転案の2択で話し合って後者になった記憶があるんですが、どちらも難しい点があり…。でもデメリット並べてみたら後者の方が圧倒的に大きそうなので、ラジオボタンの方向で考えてみます!
前者: 見た目が厳しい、ラジオボタンのルール的に選択後に決定の動作が必要で、即時フィルタリングができない(ややめんどい)
後者: 一覧するためのテーブルリストなので個々の段を露骨にボタンっぽくしたくない、がhoverアクションによる主張もスマホUIだとできないというジレンマ
@hayato24s ラジオボタンverのUIをお渡しするので、コストやスケジュール等鑑みて、可能であれば修正に含めてもらえないでしょうか。
(余裕があればで大丈夫です! 厳しければissue案件に回していいと思います)

> 「開く」「折りたたむ」という言葉のイメージからボタンを押すと...

このページ以外にも統一してアニメーションつけたいと思っており、issueとか立ててまとめてやろうかなって考えてました 。でも確かに操作感への影響が大きそうなので、可能であれば取り急ぎここだけ設定した方が良さそうですね…。
@hayato24s  頼んでも良いでしょうか🙏

> 「合計」と下のタグの選択を交互に切り替えると...

選択前と選択後で「合計」「タグごと」各領域のheightが変わっているっぽいですが、前出の問題の解決策としてラジオボタンを採用すれば同時に解決しそう…?

2022-03-31 08:49 UTC, HosokawaR approved these changes
お疲れさまです！！
タグ機能、触っていてとても楽しい機能です。

リファクタリングはフロントエンドアーキテクチャ会で話しましょう！

いま治す必要は全くありませんが、いくつか意地悪なコーナケースを掲載します。既知だったらすみません。

長いタグだとスタイルが崩れる
![image](https://user-images.githubusercontent.com/45098934/161013950-a0283252-1300-4c82-8c03-2ad6872184fe.png)

授業がない場合に「授業がありません」みたいな表示がほしい
![image](https://user-images.githubusercontent.com/45098934/161015236-533364a1-3a9e-481a-a9cc-fdef605c285d.png)

2022-03-31 11:48 UTC, hayato24s commented
>選択前と選択後で「合計」「タグごと」各領域のheightが変わっているっぽいですが、前出の問題の解決策>としてラジオボタンを採用すれば同時に解決しそう…?

これは`TagListContent`のborderの`0.4rem`の影響です

2022-03-31 13:47 UTC, hayato24s commented
### やったこと
- @HikaruEgashira さんに指摘して頂いた部分のコードを修正しました。
- `CreditFilter` の開閉ボタンの文言を`折りたたむ`から`閉じる`に変更しました。 
- `CreditFilter` にアニメーションをつけました。
- 表示する授業がないときの文言を追加しました。
    - 授業が登録されていない場合 -> 登録済みの授業がありません。
    - 条件に合致する授業が存在しない場合 -> 該当する授業がありません。
<img width="454" alt="スクリーンショット 2022-03-31 22 28 10" src="https://user-images.githubusercontent.com/68944024/161070500-75cb288d-cb0a-48ac-a96c-bea2d339fac3.png">
<img width="474" alt="スクリーンショット 2022-03-31 22 29 08" src="https://user-images.githubusercontent.com/68944024/161070549-fe1c0c19-22b8-445a-8e97-7eee3b9933e2.png">

2022-03-31 15:06 UTC, HikaruEgashira approved these changes
コードいい感じ！
ありがとう（見た目変わりそうだけどロジック変わんないからapprove）

2022-04-01 18:56 UTC, merged