Update credit page design
twin-te/twinte-front pull request #500
Opened 2022-04-01 18:55 UTC by hayato24s

- 単位数ページのデザインの変更を行いました。
- ページ遷移のところがまだできていません。
  - `route.query` を使ってやってみたのですが、うまくできませんでした。

2022-04-01 23:24 UTC, HikaruEgashira commented
ページは授業詳細と統一したいので

`credit/_tag.vue`つくって`route.params`だと動くと思う

2022-04-01 23:43 UTC, HikaruEgashira reviewed
ダークモードで文字色が違う

![image](https://user-images.githubusercontent.com/39324739/161354774-b0f74193-9075-442e-9b0f-95d8b62e6449.png)

(src/scss/main.scss:13 がもともと効いてないやんけ、、この行bodyに移動したらいい感じになる)

2022-04-02 03:35 UTC, hayato24s commented
@HikaruEgashira @HikaruEgashira 

ページ遷移も含めて実装終わりました。
あとはやることは、主に
- review をもとに修正を行う
- デバッグ
- tag-developの削除

だと思います。

2022-04-02 04:01 UTC, HikaruEgashira approved these changes
動くのでいいと思う！
パスとかはちょっと気になるけどすぐ直すことじゃないのでapprove

2022-04-02 04:01 UTC, HikaruEgashira commented on src/pages/credit/index.vue
> +export const ALL_COURSES_ID = "all-courses";
これはEntityに移動してー

2022-04-02 04:21 UTC, hayato24s commented
tag-develop 削除しました。

2022-04-02 04:36 UTC, KanadeNishizawa requested changes
ありがとうございます、めちゃいい感じです!
1点、タグが一つもないときに表示する文言が抜けているのでその修正をお願いします!

デザインデータ
https://www.figma.com/file/ofC6dBEU96Tp3IlrobCtlJ/App-V3?node-id=2746%3A24178
<img width="412" alt="スクリーンショット 2022-04-02 13 32 30" src="https://user-images.githubusercontent.com/48097323/161366375-47f1bc0f-619c-4924-87a3-d23f7389ce2d.png">

2022-04-02 05:01 UTC, KanadeNishizawa commented on src/components/TagEditor.vue
> +    <p class="tag-editor__heading">タグの編集</p>
無いとわかりにくいかもと実際に触ってみて思ったので追加しました

<img width="728" alt="スクリーンショット 2022-04-02 13 58 45" src="https://user-images.githubusercontent.com/48097323/161367046-120c043f-a499-458c-b21f-05a0dc13dfae.png">

2022-04-02 05:35 UTC, hayato24s commented
タグがない時のメッセージを追加しました。
<img width="480" alt="スクリーンショット 2022-04-02 14 25 05" src="https://user-images.githubusercontent.com/68944024/161367929-0d5a11c7-0f66-4958-b85c-00e3ed847d98.png">
<img width="432" alt="スクリーンショット 2022-04-02 14 25 21" src="https://user-images.githubusercontent.com/68944024/161367939-7dcd4e45-9b4a-4167-9243-1604c83bdbff.png">
<img width="415" alt="スクリーンショット 2022-04-02 14 31 50" src="https://user-images.githubusercontent.com/68944024/161368114-c324c74a-6147-4dd0-95bd-e18dee50dc7f.png">

2022-04-02 05:45 UTC, KanadeNishizawa approved these changes
うおお待望の単位機能
お疲れ様でした！

2022-04-02 06:25 UTC, merged