Next add directories
twin-te/twinte-front pull request #510
Opened 2022-04-03 15:31 UTC by hayato24s

Architecture ミーティングをもとにディレクトリの作成を行いました。
既存のコードは邪魔だったので `old/src` に移動しました。

```
src
|--adapter
|--application
|  |--ports
|  |--usecases
|--domain
|--gateways
|--infrastructure
|  |--api
|  |--localstorage
|--presentation
|  |--presenters
|  |--viewmodels
|--view
  |--assets
  |--components
  |--hooks
  |--pages
  |--store
  |--styles
  |--templates
```

2022-04-03 23:57 UTC, HikaruEgashira requested changes
- domain→domains
- gatewaysはあやしい（単数のもののハズなので）→repositoriesかservices
- やってる処理的にはgateways=adapter感
- DEVELOPMENT.mdにディレクトリの説明（図解）入れてほしいです（ミーティングでつかったやつ）

2022-04-04 14:24 UTC, HosokawaR commented on src/domain/index.ts
> +import Dayjs from "./datetime";
ここはどういう意図でしょうか？

`datetime.js` というファイル名で`Dayjs`を exports し、`Dayjs` という名前で使用するのはちょっとややこしいと思います。せっかく datetime(.js) といライブラリ名に依存しない抽象的な名前のファイル名なので、Dayjs という特定のライブラリ名に依存する名前になっていることに違和感を覚えました。

もし Dayjs にこだわるなら普通に Dayjs を import するのも手かと…

ちなみに僕が Dayjs という名前を避けていたのはエディタ補完で誤って node_module 以下の dayjs を直接呼び出してしまう危険性を鑑みてです。

2022-04-04 14:48 UTC, hayato24s commented
> この PR の範囲外かもしれませんが、tsconfig や prettierignore なども修正する必要がありそうです。
新機能の実装が一段落したらやりましょう！

2022-04-04 14:55 UTC, hayato24s commented on src/domain/index.ts
> +import Dayjs from "./datetime";
いい名前が思いつかなかったので一時的に`Dayjs`のままimportしていただけです。architectureを踏まえたディレクトリ構成がこのPRのメインだったので。ややこしかったですね、すみません。

個人的には`DateTime`のようなエイリアスをつけると、初見の人がパッとみて分からないと思うので、`Dayjs`を普通にimportしてそのまま使っても良いかと思います。

2022-04-04 14:58 UTC, HosokawaR commented on src/domain/index.ts
> +import Dayjs from "./datetime";
了解です！

> 個人的にはDateTimeのようなエイリアスをつけると、初見の人がパッとみて分からないと思うので、Dayjsを普通にimportしてそのまま使っても良いかと思います。

そうですね。たしかに Dayjs 独特の処理などを用いるので変に抽象化しないほうがわかりやすいかもしれません。
Dayjs import の方向性に賛同します。

2022-04-07 14:53 UTC, hayato24s commented
`domains`と`entities`ってどちらの方が良いでしょうか？
僕は`entities`の方がタイプミスしそうだなと思いました。

2022-04-16 01:30 UTC, HikaruEgashira commented
振る舞いが入ってるものをdomainと呼ぶのかが怪しいけど、
domainのほうが打ちやすいよね。
参考プロジェクトがあったらそれに合わせると認識が合いやすいかも？

2022-04-16 13:22 UTC, hayato24s commented
> 参考プロジェクトがあったらそれに合わせると認識が合いやすいかも？

この辺ですかね？

- https://github.com/twin-te/twinte-server
- https://github.com/bespoyasov/frontend-clean-architecture/tree/master/src

2022-04-17 09:54 UTC, HikaruEgashira approved these changes
ドキュメントのリファレンスに参考プロジェクトのせといて、あとは良さそう！

2022-04-17 09:54 UTC, HikaruEgashira commented on DEVELOPMENT.md
> +#### 1. Entity
この説明だとDomainsでよさそうやね

2022-04-17 10:26 UTC, merged