Fix credit page
twin-te/twinte-front pull request #522
Opened 2022-04-05 14:30 UTC by hayato24s

### やったこと
- 単位数ページの高さの調整
     - 残念ながら`height`を直接計算しています
     - iPhoneのノッチ部分を考慮しました
     - 上手くいくかはデプロイしてみないとわかりません
- タグの作成・編集でテキストフィールドを表示したときにフォーカスするようにしました
- 単位数の授業が一覧で表示されるページにおいて、授業の並び順を変更しました
     - 科目番号でソートされた授業、名前でソートされた授業の順で並び替えられます

2022-04-06 00:07 UTC, HikaruEgashira commented
focusに関して、これこそミーティングで話した共通化可能なViewModelって感じだからhooks化したい。
vueuse入ってるのでこれ試してみてほしい！

https://vueuse.org/core/useFocus/

2022-04-06 00:07 UTC, HikaruEgashira commented
focusに関して、これこそミーティングで話した共通化可能なViewModelって感じだからhooks化したい。
vueuse入ってるのでこれ試してみてほしい！

https://vueuse.org/core/useFocus/

2022-04-06 15:04 UTC, hayato24s commented
> focusに関して、これこそミーティングで話した共通化可能なViewModelって感じだからhooks化したい。 vueuse入ってるのでこれ試してみてほしい！
> 
> https://vueuse.org/core/useFocus/

[github vueuse useFocus](https://github.com/vueuse/vueuse/blob/main/packages/core/useFocus/index.ts)

カスタムコンポーネントだと`input`タグに直接アクセスすることが難しいため、vueuseは使わずに自作しました。

カスタムコンポーネントに`ref`を指定する場合は、カスタムコンポーネント自体に`focus`イベントを設定する必要があるのだと思われます。

2022-04-07 19:33 UTC, KanadeNishizawa approved these changes
(focus時の枠考えないとですね…)

お疲れ様です、あざす！

2022-04-08 00:40 UTC, HikaruEgashira requested changes
天才！
レビュー遅れてごめんね。コメントのとこ気になったので聞きたい！

2022-04-08 00:40 UTC, HikaruEgashira commented on src/components/TagEditor.vue
> +    );
`handleClick`を
```ts
    const handleClick = () => {
      tagName.value = "";
      emit("update:add", true);
      nextTick(() => focus(["input"]));
    };
```
と同じ？

2022-04-08 00:40 UTC, HikaruEgashira commented on src/hooks/useFocus.ts
> +  };
ここにnextTick入れていいと思う

nextTickいらないケースもあると思うから入れてないんだと思うけど、
さほどパフォーマンスに影響でないと思うのでわかりやすさ重視で

2022-04-08 00:40 UTC, HikaruEgashira commented on src/pages/credit/index.vue
> +    100vh - env(safe-area-inset-top) - env(safe-area-inset-bottom) - 19.6rem
ヘッダーの高さとこの値、
変数化したいね（このPRでする必要はない）

2022-04-08 14:53 UTC, hayato24s commented on src/components/TagEditor.vue
> +    );
同じですね。修正します！

2022-04-08 14:53 UTC, hayato24s commented on src/hooks/useFocus.ts
> +  };
了解です。

2022-04-08 15:13 UTC, hayato24s commented
@HikaruEgashira 
ご指摘いただいたところの修正終わりました！

2022-04-08 15:17 UTC, HikaruEgashira approved these changes
ありがと！！！

2022-04-08 15:18 UTC, HikaruEgashira commented
マージ後デプロイお願いしますー

2022-04-08 15:31 UTC, merged