Feature/add usecases
twin-te/twinte-front pull request #561
Opened 2022-08-09 14:43 UTC by hayato24s

ユースケースの追加を行いました。

コミットが汚くなってしまったので、[add usecases](https://github.com/twin-te/twinte-front/commit/07100d84e4be106d78650d8af76b746bad2f9608)以降から確認してもらえると助かります。

2022-08-10 00:04 UTC, HikaruEgashira requested changes
レビュー遅れそうなのでスマホレビュー

2022-08-10 00:04 UTC, HikaruEgashira commented on src/application/usecases/user/getSetting.ts
> +  const setting = getKeysFromObj(settingInitialValue).reduce((setting, key) => {
```suggestion
  const setting = {...settingInitialValue, ...result}
```
なデータ構造

2022-08-10 13:48 UTC, hayato24s commented on src/application/usecases/tag/updateTagOrders.ts
> + */
英語できないのバレますね笑

2022-08-10 13:51 UTC, hayato24s commented on src/application/usecases/others/sendFeedback.ts
> +  null,
ここはOk.valueの型になるのでvoidが使えないんですよね。

```
export class Ok<T = unknown> {
  constructor(readonly value: T) {}
  type = "ok" as const;
  isOk(): this is Ok<T> {
    return true;
  }
  isErr(): this is Err {
    return false;
  }
}

export class Err<E = ResultError> {
  constructor(readonly value: E) {}
  type = "err" as const;
  isOk(): this is Ok {
    return false;
  }
  isErr(): this is Err<E> {
    return true;
  }
}

export type Result<T, E extends ResultError> = Ok<T> | Err<E>;

export type PromiseResult<T, E extends ResultError> = Promise<Result<T, E>>;
```

2022-08-10 14:01 UTC, hayato24s commented on src/application/usecases/others/getCurrentModule.ts
> +          "The information about module is inappropriate."
表示に関することは全てViewのレイヤーでやろうと思っています。フォルダ的にはuiに相当します。

2022-08-10 14:04 UTC, HosokawaR commented on src/application/usecases/others/getCurrentModule.ts
> +          "The information about module is inappropriate."
たしかに英語表記とかも見据えたりもすると、表記の責務は View のほうが楽かもしれませんね

2022-08-10 14:07 UTC, HosokawaR commented on src/application/usecases/others/sendFeedback.ts
> +  null,
`never` とか使えないんでしたっけ？
なんとなく `null` よりは返り値がないことが表現できないかと

2022-08-10 14:27 UTC, hayato24s commented on src/application/usecases/index.ts
> +module.exports = {
ecmascriptとcommonjsの違いについてよくわかっていないのですが、調べてみたら以下のような違いがあるらしいです。

ES
- client-side & javascript で使用される
- export & import

commonjs
- server-side & node.js で使用される
- require & module.exports

つまり、ここはexportを使用して書く必要がありそうです。

2022-08-11 05:26 UTC, HikaruEgashira commented on src/application/usecases/others/getCurrentModule.ts
> +          "The information about module is inappropriate."
了解

2022-08-11 05:47 UTC, HikaruEgashira commented on src/application/usecases/index.ts
> +module.exports = {
> server-side & node.js で使用される

は怪しいけど、ESとCommonJSはモジュールシステムが別だからインポートすらできなくなってる（検証済み）
脱CommonJSにご協力お願いします。（なおconfig系、、）

2022-08-11 06:13 UTC, HikaruEgashira commented on src/application/usecases/others/sendFeedback.ts
> +  null,
`new Ok(...)`って値が返ってくるから確かにvoidじゃないな、、
ここはnullでいいと思います！

今の実装だと、`new Ok()`ができないから、`?`つけて、

```ts
export class Ok<T = unknown> {
  constructor(readonly value?: T) {}
  type = "ok" as const;
  isOk(): this is Ok<T> {
    return true;
  }
  isErr(): this is Err {
    return false;
  }
}
```

のほうが使いやすそうに感じたけどどうでしょう？
adapter実装時に勝手に変えてください！！

## never

> ある種の操作（特に、例外の送出や継続の呼び出し）が戻ってこないはずであるという真実を表現するのに大変都合がよい...引用元TaPL

が自分のneverに対する気持ちで、`throw‘時に使うのが向いてるイメージです！

2022-08-12 06:34 UTC, HikaruEgashira approved these changes
いい感じです！

2022-08-12 07:07 UTC, merged