Feature/add UI
twin-te/twinte-front pull request #566
Opened 2022-09-07 16:20 UTC by hayato24s

変更が多くなってしまいすみません🙇‍♂️
多少はコミットで分けています。

## 主な変更点
- presentation層の追加
- uiの追加
  - defineComponent -> setup script
- Repositoryを選択できるように
  - [ここ](https://github.com/twin-te/twinte-front/blob/feature/add-ui/src/adapter/index.ts)からできます
- prettierのprintWidthを120に

2022-09-08 10:43 UTC, HosokawaR commented on .prettierrc
> +  "printWidth": 120
ご存知かもしれませんが `printWidth` は 1行の最大文字数ではありません。
https://prettier.io/docs/en/options.html#print-width

ですのでもし「現代のエディタに横幅 80 文字は短すぎる」という意図で変えたなら再考する余地があるかもしれません。

また個人的には少しはみ出してつらいですね。
画像は FHD 等倍のディスプレイのスクショです。
ここらへんは個人の環境によりますが…

120
はみ出ている行は横スクロールしないと見えないです。
![image](https://user-images.githubusercontent.com/45098934/189102480-c7b4ce14-9db1-4913-9cf4-bccd3efe534a.png)

80
きれいな感じで収まっています。
![image](https://user-images.githubusercontent.com/45098934/189102526-8c7d4224-39fa-4e48-bf6a-5b412cf71bd4.png)

2022-09-12 08:16 UTC, hayato24s commented on .prettierrc
> +  "printWidth": 120
僕の使っているモニターでは120がちょうど良かったので、変更していました。
prettierのドキュメントには80以上にはしないようにと書いてあるので、80にしましょう！

2022-09-13 02:09 UTC, HikaruEgashira approved these changes
使いやすい形でいいと思います！

2022-09-14 16:03 UTC, hayato24s commented
> 見るのが遅れてすみません…今週忙しく日曜日に確認します…m(_ _)m

いえいえ、僕の方こそ、変更が多くなってしまって申し訳ないです。ゆっくりで大丈夫です！気長にやっていきましょう！

2022-09-19 11:31 UTC, HosokawaR commented on src/adapter/index.ts
> +const dev = true;
`dev`の値は後からいい感じに取ってくる値でしょうか？
（単に忘れただけではないか一応確認）

2022-09-19 12:15 UTC, HosokawaR commented
大量の変更お疲れ様です＆ありがとうございます！
すごく見通しのいいコードになったと思いました！！

2022-09-20 08:17 UTC, HosokawaR requested changes

2022-09-21 14:39 UTC, hayato24s commented on src/adapter/index.ts
> +const dev = true;
当初は環境変数から設定しようと思っていましたが、その場合apiを使用して実装したレポジトリのデバッグができないため断念しました。

`dev`のデフォルト値は`false`に変更しますね。

2022-09-21 14:39 UTC, hayato24s commented on src/utils.ts
> +export const uuid = (): string => {
何かいい感じの名前とかありますか？

`createId`とかでしょうか？

2022-09-22 10:41 UTC, HosokawaR commented on src/utils.ts
> +export const uuid = (): string => {
`createId` いいですね！
公開するライブラリとかではないので、`uuid()` でなければそこまでこだわらなくてもいいと思います。

2022-09-23 07:02 UTC, HosokawaR commented on src/utils.ts
> +export const uuid = (): string => {
https://github.com/twin-te/twinte-front/pull/566/commits/b12273409901f26c35dc916d71616f9cebc59c04 で解決

2022-09-23 07:03 UTC, HosokawaR commented on .prettierrc
> +  "printWidth": 120
了解です！
https://github.com/twin-te/twinte-front/pull/566/commits/882e2ba5aefccec58029e905583d3b42f299e03d で解決

2022-09-23 07:09 UTC, HosokawaR approved these changes
おつかれさまですー！
細かい点ですが対応してもらいありがとうございます。

やっと old_src が削除できて感慨深いものがありますね

2022-09-23 08:57 UTC, merged